### ISSUE TITLE
Special Code word, for recording

### ISSUE THREAD

**Issue by tingtongdpnw** [jhj0517/Whisper-WebUI#108]
Is there a way, for example, to include a code word, period and comma in the output of the microphone voice recording? As far as i know Whisper Openai is automatically putting periods and commas. But my coworker is asking for it, because he thinks its better to use it like that.

**Comment by jhj0517** [comment]
I'm not sure about your problem, but you can achieve your logic after splitting the string with `.split()` for example.
If the issue persists, feel free to repost.
