### ISSUE TITLE
Error Encountered During Faster-Whisper Update (cublas64_12.dll Missing)

### ISSUE THREAD

**Issue by mentesdeltiempo** [jhj0517/Whisper-WebUI#111]
Thank you for your attention to the community.

I have tried updating to faster-whisper 1.0.1 but I have this error:

Error transcribing file on line Library cublas64_12.dll is not found or cannot be loaded
\Whisper-WebUI-master\venv\lib\site-packages\torch\cuda\memory.py:330: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(
Traceback (most recent call last):
  File "\Whisper-WebUI-master\venv\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "\Whisper-WebUI-master\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "\Whisper-WebUI-master\venv\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "\Whisper-WebUI-master\venv\lib\site-packages\gradio\blocks.py", line 1397, in postprocess_data
    self.validate_outputs(fn_index, predictions) # type: ignore
  File "\Whisper-WebUI-master\venv\lib\site-packages\gradio\blocks.py", line 1371, in validate_outputs
    raiseValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values ​​(needed: 2, received: 1).
Wanted outputs:
    [textbox, file]
Received outputs:
    [None]

I tried changing CUDA to the requested version but the error persists

This problem also occurs with faster-whisper 1.0.1 and 1.0.0

OS: Windows 11

greetings.

**Comment by jhj0517** [comment]
Hi. Can you try
``` 
nvcc --version
```
and see what it prints out? This bug should not happen if you normally update your CUDA version.

**Comment by mentesdeltiempo** [comment]
Apparently I assumed that having installed Nvidia App and finding CUDA 12 in the root of the installation would work Whisper-WebUI.

I reinstalled CUDA only and the problem was solved.

nvcc --version test:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
