### ISSUE TITLE
After the transcription using the large-v3 model, there are irrelevant subtitles at the beginning of the caption

### ISSUE THREAD

**Issue by jeshs** [jhj0517/Whisper-WebUI#118]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]
Colab

After the transcription using the large-v3 model, there are irrelevant subtitles at the beginning of the caption:

1
00:00:00,000 --> 00:00:02,000
This video is a derivative work of the Touhou Project.

2
00:00:02,000 --> 00:00:04,000
It contains violence, sex, and inappropriate language.

3
00:00:04,000 --> 00:00:06,000
Viewer discretion advised.

**Comment by jhj0517** [comment]
It's most likely a Whisper hallucination. 
- related issue
   - https://github.com/openai/whisper/discussions/679

There is a "prompt" option that you can use as a parameter in Whisper. 
To my understanding, it's a parameter that can help Whisper understand the context of the transcription.
But I didn't include it in my WebUI. Maybe I should have added it as a parameter

**Comment by jhj0517** [comment]
`initial_prompt` has been added in #141

**Comment by jeshs** [comment]
Great job!
