### ISSUE TITLE
Compared to the official whisper, the accuracy of the GUI is reduced

### ISSUE THREAD

**Issue by shuiqingliu** [jhj0517/Whisper-WebUI#119]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]
Linux Ubuntu Cude

The same file has much higher accuracy with the official version, is this related to the modified version of whisper?

**Comment by jhj0517** [comment]
Hi, I've just compared [whisper](https://github.com/openai/whisper) and [faster-whisper](https://github.com/SYSTRAN/faster-whisper) using some samples, but they produced the same results.
Could you provide more information to reproduce? For example, samples you used ( such as YouTube URLs ) and  which model you used.

**Comment by jhj0517** [comment]
This might be related to #123, which involved using the wrong version of pytorch, but it was fixed in #124.
If you encounter a similar issue again, please feel free to re-open!
