### ISSUE TITLE
Obsolete cuda version

### ISSUE THREAD

**Issue by Koro33** [jhj0517/Whisper-WebUI#123]
I've noticed that we are still using pytorch with CUDA 11

https://github.com/jhj0517/Whisper-WebUI/blob/87ae7385629b8c0bbd092e55e66c9c371494169e/requirements.txt#L1

Are there any compatibility problems leading to this? Should we upgrade to CUDA 12

```
--extra-index-url https://download.pytorch.org/whl/cu121
```

I'm trying to reduce the docker image size by not using nvidia/cuda:12 base image. It's so wired that although pip installed pytorch with CUDA 11, it still search CUDA 12 libs and raised an error `Error transcribing file on line Library libcublas.so.12 is not found or cannot be loaded`.

**Comment by jhj0517** [comment]
Thanks for pointing this out! 
Indeed, I should've paid attention to the torch version when upgrading faster-whisper to 1.0.0. 
Fixed this in #124!
