### ISSUE TITLE
Google Drive File Paths for Input and Output

### ISSUE THREAD

**Issue by jhj0517** [jhj0517/Whisper-WebUI#129]
Someone expressed interest in using file paths from Google Drive instead of uploading large files directly through Gradio. 
Utilizing Google Drive file paths could be helpful.

**Comment by starloreh** [comment]
I thought that was the purpose of "Input Folder Path" in colab. I thought I was writing the google drive file path wrong. :smile:

**Comment by jhj0517** [comment]
@starloreh You can use it like that, if you just add the code that mounts google drive in the notebook.
I think I should add it to the notebook, I'll work on it later.
