### ISSUE TITLE
Adding REST/swagger API and docker image in the official repo

### ISSUE THREAD

**Issue by flefevre** [jhj0517/Whisper-WebUI#137]
Dear whisper webui team, 
i would like to know if your program could be install on a linux server.
it seems there is no official docker image, are you going to this direction?
i would like to know also if you provide a rest/swagger api to be able to call your program directly?
Thanks for the work done.
François from France

**Comment by jhj0517** [comment]
Hi.
1. Here's the [Dockerfile](https://github.com/jhj0517/Whisper-WebUI/blob/master/Dockerfile) you can use. 

2. Regarding REST API, you can build it in gradio by setting`api_open=True`.
After setting it, you'll see such things in footer of the app.

![image](https://github.com/jhj0517/Whisper-WebUI/assets/97279763/9335fe81-2ee2-4ca3-acf7-fc803d8c2daf)

If you click on "Use via API", you'll see documentation like this:
![image](https://github.com/jhj0517/Whisper-WebUI/assets/97279763/ca0ad3db-4f45-4de6-a3e3-438df762ba8e)

You can call it like, `http://localhost:7860/transcribe_file`.

I'll add `api_open` as a command line argument!
