### ISSUE TITLE
Could not load library libcudnn_ops_infer.so.8.

### ISSUE THREAD

**Issue by AitNev** [jhj0517/Whisper-WebUI#140]
**Which OS are you using?**
 - OS: Linux
 
 With the default installation `bash Install.sh` and Only when using the Faster Whisper implementation i get this error message when trying to transcribe with whisper:
```
venv ./venv/bin/python

Use Faster Whisper implementation
Device "cuda" is detected
Running on local URL:  http://0.0.0.0:8860

To create a public link, set `share=True` in `launch()`.
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
start-webui.sh: line 7: 141135 Aborted                 $PYTHON ./app.py --server_name 0.0.0.0 --server_port 8860
launching the app
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
```
 - One way to avoid this issue was adding in `start-webui.sh` the flag `--disable_faster_whisper` runs slower but it doesn't throw an error

The way it was fixed from this [comment](https://github.com/SYSTRAN/faster-whisper/issues/516#issuecomment-1972615012) where by only doing the second step, adding to `requirements.txt` 
```
nvidia-cublas-cu11
nvidia-cudnn-cu11
```
And then exporting their path by adding this line inside `start-webui.sh` before executing `app.py`
```
export LD_LIBRARY_PATH=`$PYTHON -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`
```
With that I was able to get faster-whisper working but just the nvidia libraries weight 1GB, I'm not sure if someone is able to get it running without those libraries. 
At least this might help someone who stumbles on this issue.

**Comment by AitNev** [comment]
Already was this [issue 114](https://github.com/jhj0517/Whisper-WebUI/issues/114)

**Comment by jhj0517** [comment]
Hi, Thanks for reporting. It seems this happens on Linux & ubuntu.
Just noting some related issues here:
- #114
- [faster-whisper #297](https://github.com/SYSTRAN/faster-whisper/issues/297#issuecomment-1592570614)
- [faster-whisper #729](https://github.com/SYSTRAN/faster-whisper/issues/729#issuecomment-2023062777)

**Comment by jhj0517** [comment]
duplicate with #271, if anyone faced the same error refer to https://github.com/jhj0517/Whisper-WebUI/issues/271#issuecomment-2350820352
