### ISSUE TITLE
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. transformers 4.40.0 requires tokenizers<0.20,>=0.19, but you have tokenizers 0.15.2 which is incompatible.

### ISSUE THREAD

**Issue by che2ze** [jhj0517/Whisper-WebUI#142]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]

[Google Colab]

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 4.40.0 requires tokenizers<0.20,>=0.19, but you have tokenizers 0.15.2 which is incompatible.

**Comment by jhj0517** [comment]
Hi, Thanks for reporting this. 
It seems like colab downgrade its default transformers versions from `4.40.1` to `4.40.0` ? 

I'll fix it soon!

**Comment by jhj0517** [comment]
This is fixed in #143, please re-open the issue if issue persists!
