### ISSUE TITLE
Make length of silence adjustable

### ISSUE THREAD

**Issue by sbolten** [jhj0517/Whisper-WebUI#158]
Currently silence needs to something like 4 seconds long to be identified and create the next section.
I could not find a way to adjust this. What I would like to have is a parameter where I can define how long the silence is before a new section is created.

**Comment by jhj0517** [comment]
Hi!

>> parameter where I can define how long the silence is before a new section is created.

This is what the Silero VAD Filter can do. Currently the Silero VAD Filter is implemented only within faster-whisper, 
but I'll add the Silero VAD Options parameter to the WebUI anyway.

**Comment by jhj0517** [comment]
"VAD Options" tab is added in #159, 

To get what you want, I think decreasing "Minimum Silence Duration (ms)" would be helpful.
![5142142](https://github.com/jhj0517/Whisper-WebUI/assets/97279763/8019ce13-5f69-4a9b-b3c3-0190abbb3c85)

Make sure to check "Enable Silero VAD Filter" checkbox to use VAD filter.

**Comment by sbolten** [comment]
Very nice. Thx a lot. Will try on Monday when back at my desk.

**Comment by jhj0517** [comment]
please re-open this if you face any error!
