### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by 21-ko** [jhj0517/Whisper-WebUI#162]
**Which OS are you using?**
 - OS: Colab

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 4.41.1 requires tokenizers<0.20,>=0.19, but you have tokenizers 0.15.2 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
faster-whisper 1.0.1 requires tokenizers<0.16,>=0.13, but you have tokenizers 0.19.1 which is incompatible.

**Comment by jhj0517** [comment]
Hi, this is fixed in #163,
Please let me know and re-open the issue if the problem persists!
