### ISSUE TITLE
I want to be able to use Whisper kotoba-whisper-v1.0 model

### ISSUE THREAD

**Issue by cookiexND** [jhj0517/Whisper-WebUI#164]
kotoba-whisper-v1.0 seems to have a high recognition rate for Japanese.
I would like to use kotoba-whisper-v1.0 in the UI of Whisper-WebUI by selecting kotoba-whisper-v1.0 in the pulldown like other models.
Could you please add the functionality or point me in the right direction?
Thank you in advance.

Whisper kotoba-whisper-v1.0 model
https://huggingface.co/kotoba-tech/kotoba-whisper-v1.0-faster

**Comment by jhj0517** [comment]
Enabling fine-tuned model is good idea. I'll work on it

**Comment by jhj0517** [comment]
#165 is merged and fine-tuned model for faster-whisper is enabled.

Place the model in `\models\Whisper\faster-whisper\`
Then you can run the model.

**Comment by cookiexND** [comment]
When I reinstalled, I got an error saying that the path to “models\Whisper\faster-whisper\” was missing! error appeared. I created the respective folders under “models” and placed the desired models there, and it ran without problems.

Glad you responded so quickly, I really appreciate the flawless work.

**Comment by jhj0517** [comment]
@cookiexND 
Fixed in #167,
 Please re-open and let me know if it persists!
