### ISSUE TITLE
 Can I install it on the MacOS system？

### ISSUE THREAD

**Issue by Fanlen** [jhj0517/Whisper-WebUI#169]
The GPU container cannot be started on macos because there is no GPU option available？The working environment I am using is M2 max studio

**Comment by jhj0517** [comment]
Hi, Did you face the error while running Docker or running shell script?

**Comment by Fanlen** [comment]
> 您好，您在运行 Docker 或运行 shell 脚本时遇到错误吗？

./start-webui.sh
venv ./venv/bin/python

Use Faster Whisper implementation
Device "cpu" is detected
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
./start-webui.sh: line 7:  4026 Segmentation fault: 11  $PYTHON ./app.py
launching the app
./start-webui.sh: line 11: deactivate: command not found
eben@mingdeMBP Whisper-WebUI-master % /usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

运行能启动ui，然后上传mp4，然后选择small model和language,然后能看到开始下载模型，然后终端如上提示，并出现python意外退出，部分报告代码：
ranslated Report (Full Report Below)
-------------------------------------

Process:               Python [4026]
Path:                  /usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.12.3 (3.12.3)
Code Type:             X86-64 (Native)
Parent Process:        Exited process [4025]
Responsible:           Terminal [2044]
User ID:               501

Date/Time:             2024-06-17 17:10:54.8123 +0800
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        8E2BF9FF-BBA3-A31F-CBE3-CB31BC82EBDF


Time Awake Since Boot: 16000 seconds

System Integrity Protection: enabled

Crashed Thread:        18

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000600
Exception Codes:       0x0000000000000001, 0x0000000000000600

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [4026]

VM Region Info: 0x600 is not in any region.  Bytes before following region: 4506208768
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10c975000-10c977000    [    8K] r-x/r-x SM=COW  /usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff801800e46 __semwait_signal + 10
1   libsystem_c.dylib             	    0x7ff8016f3a61 nanosleep + 199
2   Python                        	       0x10d723cdf time_sleep + 159
3   Python                        	       0x10d64f550 _PyEval_EvalFrameDefault + 53829
4   Python                        	       0x10d55a882 method_vectorcall + 373
5   Python                        	       0x10d557ee7 _PyVectorcall_Call + 138
6   Python                        	       0x10d650644 _PyEval_EvalFrameDefault + 58169
7   Python                        	       0x10d64214f PyEval_EvalCode + 197
8   Python                        	       0x10d6a8249 run_eval_code_obj + 83
9   Python                        	       0x10d6a64e0 run_mod + 107
10  Python                        	       0x10d6a5b1d pyrun_file + 133
11  Python                        	       0x10d6a5025 _PyRun_SimpleFileObject + 287
12  Python                        	       0x10d6a4cde _PyRun_AnyFileObject + 148
13  Python                        	       0x10d6c9413 pymain_run_file_obj + 226
14  Python                        	       0x10d6c90c6 pymain_run_file + 89
15  Python                        	       0x10d6c8956 Py_RunMain + 1005
16  Python                        	       0x10d6c8a8c Py_BytesMain + 42
17  dyld                          	    0x7ff8014b2366 start + 1942

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff801839ac0 start_wqthread + 0

Thread 2:
0   libsystem_kernel.dylib        	    0x7ff8018030ae kevent + 10
1   loop.cpython-312-darwin.so    	       0x1312288fc uv__io_poll + 988
2   loop.cpython-312-darwin.so    	       0x1312169e1 uv_run + 433
3   loop.cpython-312-darwin.so    	       0x131144e9c __pyx_f_6uvloop_4loop_4Loop___run + 44
4   loop.cpython-312-darwin.so    	       0x13114516b __pyx_f_6uvloop_4loop_4Loop__run + 539
5   loop.cpython-312-darwin.so    	       0x13119b8ac __pyx_pw_6uvloop_4loop_4Loop_25run_forever + 828
6   loop.cpython-312-darwin.so    	       0x131137b97 __Pyx_PyObject_CallNoArg + 103
7   loop.cpython-312-darwin.so    	       0x13119e088 __pyx_pw_6uvloop_4loop_4Loop_45run_until_complete + 1384
8   Python                        	       0x10d5635ab method_vectorcall_O + 98
9   Python                        	       0x10d64e621 _PyEval_EvalFrameDefault + 49942
10  Python                        	       0x10d55a8e3 method_vectorcall + 470
11  Python                        	       0x10d650644 _PyEval_EvalFrameDefault + 58169
12  Python                        	       0x10d55a8e3 method_vectorcall + 470
13  Python                        	       0x10d721e10 thread_run + 124
14  Python                        	       0x10d6b8b91 pythread_wrapper + 40
15  libsystem_pthread.dylib       	    0x7ff80183e18b _pthread_start + 99
16  libsystem_pthread.dylib       	    0x7ff801839ae3 thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	    0x7ff801800f7a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff80183e6f3 _pthread_cond_wait + 1211
2   loop.cpython-312-darwin.so    	       0x1312244d9 uv_cond_wait + 9
3   loop.cpython-312-darwin.so    	       0x131212266 worker + 86
4   libsystem_pthread.dylib       	    0x7ff80183e18b _pthread_start + 99
5   libsystem_pthread.dylib       	    0x7ff801839ae3 thread_start + 15

Thread 4:
0   libsystem_kernel.dylib        	    0x7ff801800f7a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff80183e6f3 _pthread_cond_wait + 1211
2   loop.cpython-312-darwin.so    	       0x1312244d9 uv_cond_wait + 9
3   loop.cpython-312-darwin.so    	       0x131212266 worker + 86
4   libsystem_pthread.dylib       	    0x7ff80183e18b _pthread_start + 99
5   libsystem_pthread.dylib       	    0x7ff801839ae3 thread_start + 15

。。。。。




下面我的环境信息：
Model: MacBookPro11,3, BootROM 478.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.5 GHz, 16 GB, SMC 2.19f12
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe, 2 GB
Display: Color LCD, 2880 x 1800 Retina, Main, MirrorOff, Online
Display: S2700, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1772.1)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: USB30Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: 2.4G Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by Fanlen** [comment]
> Hi, Did you face the error while running Docker or running shell script?

After pulling the new code, it will work fine. Thank you
