### ISSUE TITLE
T2T translate "Something went wrong Connection errored out."

### ISSUE THREAD

**Issue by fullyanthorney** [jhj0517/Whisper-WebUI#17]
![image](https://github.com/jhj0517/Whisper-WebUI/assets/47101121/967042e9-b3bf-41d0-931e-b7460352c9a2)
![image](https://github.com/jhj0517/Whisper-WebUI/assets/47101121/813a33c2-fd19-468c-b258-838f2c563699)

1. colab 환경에서 해당 레포 clone 후 진행했습니다.
2. Youtube 탭에서 srt 자막파일 생성은 정상적으로 작동했습니다.
3. T2T translate 탭에서 자막파일 업로드 후 실행시 위 사진처럼 나오면서 실패합니다. 에러 메시지도 안뱉어서 뭐가 문제인지를 모르겠어요.. ㅜ

**Comment by jhj0517** [comment]
안녕하세요 @fullyanthorney 님. 방금 코랩에서 에러를 재생산하려고 해봤습니다.
코랩 무료버전 (GPU 가 아닌 CPU 버전) 에서 발생하는 문제 같습니다.
무료버전을 사용할 때, nllb 모델이 제대로 다운로드 되지 않습니다.

GPU (A100) 런타임에서 테스트 했을 때, 정상적으로 작동하는 것을 확인하였습니다.

**Comment by fullyanthorney** [comment]
감사합니다!!
