### ISSUE TITLE
괄호나 기호 같은것들도 srt이름에 적용되게 가능한가요?

### ISSUE THREAD

**Issue by SeongGyu1216** [jhj0517/Whisper-WebUI#171]
예를들어 &, ",  ;, (), [] 등등 같이 기호나 특수문자는 srt가 생성될 때 이름에 적용이 안되더라구요. 이거는 유니코드문제때문에 안되는건가요? 해결해주실 수 있나요?

그리고 GIthub에서 수동설치가 아닌 자동으로 설치되게하려면 Venv 폴더를 지우고 Install.bat을 실행하면 되나요?

**Comment by jhj0517** [comment]
안녕하세요!

>>  &, ", ;, (), [] 등등 같이 기호나 특수문자는 srt가 생성될 때 이름에 적용이 안되더라구요.

Gradio 에서 `gr.Files()` 에 파일을 업로드 시 Temp 폴더에서 특수문자들을 자동으로 제거해버리기 때문에, WebUI 에서 할 수 있는 것이 없습니다. 여러 OS 에서 파일 이름에서 금지된 특수 문자들을 사용하는 것을 방지하기 위한 것으로, 아마도 Gradio 에서 이 방식이 변경되지는 않을 것 같습니다.

>> 자동으로 설치되게하려면 Venv 폴더를 지우고 Install.bat을 실행하면 되나요?

만일 설치 요소들을 전부 제거하고 다시 재설치를 원하신다면 그렇게 하시는 것이 맞습니다.
혹시 업데이트만을 원하신다면, 업데이트 시 마다 `git pull origin master`를 하셔야 하는데, 편리함을 위해 나중에 `update.bat` 같은 스크립트를 추가하는 것이 나을 것 같습니다.

**Comment by SeongGyu1216** [comment]
알려주셔서 감사합니다!

혹시 update.bat 파일은 어떻게하면 만들 수 있는건가요?

**Comment by jhj0517** [comment]
@SeongGyu1216 제가 나중에 추가할 수 있도록 하겠습니다!

**Comment by SeongGyu1216** [comment]
감사합니다

**Comment by jhj0517** [comment]
#172 에서 개선되었습니다.

[Whisper-WebUI-Runner-v1.0.0](https://github.com/jhj0517/Whisper-WebUI/releases/tag/v1.0.0) 에서 OS와 호환되는 `Whisper-WebUI.zip` 파일을 다운로드 받으신 후 각각의 스크립트를 실행하시면 됩니다.

설치 : `Install.bat` / `install.sh` 
시작 : `start-webui.bat` / `start-webui.sh`
업데이트 : `update.bat` / `update.sh`

혹시 사용 중에 문제가 생긴다면 언제든지 이슈를 재 오픈 해주시면 감사합니다!

**Comment by SeongGyu1216** [comment]
감사합니다!
