### ISSUE TITLE
Apple MBS support Not found in the master branch

### ISSUE THREAD

**Issue by Fanlen** [jhj0517/Whisper-WebUI#180]
The current master branch does not seem to have added support for Apple MBS in this link https://github.com/jhj0517/Whisper-WebUI/pull/170

**modules/faster_whisper_inference.py Not found**

      if torch.cuda.is_available():
            self.device = "cuda"
        elif torch.backends.mps.is_available():
            self.device = "mps"
        else:
            self.device = "cpu"

**modules/whisper_Inference.py Not found**

**Comment by jhj0517** [comment]
Hi. To integrate various whisper implementations including faster-whisper, insanely-fast-whisper.. etc,
I created an abstract class `WhisperBase()` and moved the device setting logic into there:
https://github.com/jhj0517/Whisper-WebUI/blob/a230be5f0ac28e6947a44d78e3e71cdaab8a6890/modules/whisper_base.py#L321-L328

It will detect the mps device when the script starts. But if you don't see the 
```
device "mps" is detected
```
when you run the shell script, please let me know.

**Comment by Fanlen** [comment]
@jhj0517  thks,  My devies is Apple M2 Ultra 64G,run Install. sh and then run start webui. sh, the error message appears as follows:
 ./start-webui.sh 
  venv ./venv/bin/python
 /Users/hengshi/Case/Whisper-WebUI/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Use "faster-whisper" implementation
Device "mps" is detected
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
model.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.09G/3.09G [02:10<00:00, 8.84MB/s]
Error transcribing file: unsupported device mps
Traceback (most recent call last):
  File "/Users/hengshi/Case/Whisper-WebUI/venv/lib/python3.9/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/Users/hengshi/Case/Whisper-WebUI/venv/lib/python3.9/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/hengshi/Case/Whisper-WebUI/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1856, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/hengshi/Case/Whisper-WebUI/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1634, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/Users/hengshi/Case/Whisper-WebUI/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1610, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x327259190>, <gradio.templates.Files object at 0x3272591c0>]
Received outputs:
    [None]

**Comment by jhj0517** [comment]
Thanks for reporting this. 
This should be fixed in #182. 

But I don't know if faster-whisper actually supports the "mps" device. 
In faster-whisper, they say available devices are: `("cpu", "cuda", "auto")`.

**Comment by Fanlen** [comment]
@jhj0517 
After the update, it is perfect to run and use the APP device MPS, and the speed has improved significantly. Thank you again for the author's efforts
