### ISSUE TITLE
translator input_length is bigger than 0.9 * max_length: 200

### ISSUE THREAD

**Issue by Fanlen** [jhj0517/Whisper-WebUI#189]
Use facebook/nllb-200-3.3B translation info:
```
Your input_length: 223 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
Your input_length: 223 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
```

When translating SRT, the problem is as described above: Where should I increase this length, or do I have specific parameters to set? If it really doesn't work, I need to handle the SRT segmentation. Can I include this parameter as a possibility or provide some suggestions? Thank you

**Comment by jhj0517** [comment]
Thanks for reporting this. 
I didn't know there was such a parameter, it's added in #190.

You can adjust the "Max Length Per Line" value and increase it if the message appears. 
The default value is 200.

**Comment by jhj0517** [comment]
please feel free to re-open this if the issue persists!
