### ISSUE TITLE
VAD VadOptions unexpected keyword argument 'window_size_samples'

### ISSUE THREAD

**Issue by viebrix** [jhj0517/Whisper-WebUI#197]
### Which OS are you using?
 - OS: Linux Mint
### Which Whisper Version?
- faster-whisper==1.0.3

Hello thanks for the further improvements since I tested your software with my AMD GPU 580. In the meantime I bought a NVidia Card 3060ti and now I wanted to test the new features for faster-whisper.
Since I had hallucinations with german language I wanted to test with VAD activated.
But setting VAD Option to true in gradio leads to following error, after starting "Generate Subtitle File":
**Console Output:**
```
To create a public link, set `share=True` in `launch()`.
Error transcribing file: VadOptions.__new__() got an unexpected keyword argument 'window_size_samples'
Traceback (most recent call last):
  File "................software/whisper-webui/Whisper-WebUI/venv/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "................software/whisper-webui/Whisper-WebUI/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "................software/whisper-webui/Whisper-WebUI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1856, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "................software/whisper-webui/Whisper-WebUI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1634, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "................software/whisper-webui/Whisper-WebUI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1610, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x7f376b941210>, <gradio.templates.Files object at 0x7f376b9412a0>]
Received outputs:
    [None]

```
### Additional Info
Maybe I should mention that I had problems with different cuda libs. I could solve these problems with the hints in issues for LD_LIBRARY_PATH and with installing 
`pip3 install torch==2.1.0+cu121 torchvision==0.16.0+cu121 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu121`

**Comment by jhj0517** [comment]
Hi. It seems that `window_size_samples` is deprecated in faster-whisper 1.0.3.

I'll work on a migration from 1.0.2 to 1.0.3 in faster-whisper!

**Comment by viebrix** [comment]
thanks a lot :)

**Comment by jhj0517** [comment]
Migration has done in #198. 
Please feel free to re-open if you face any error!

**Comment by viebrix** [comment]
Wow really incredible fast update. Everything has worked. Thank you!!!
Only one question in faster_whisper I found an option: hallucination_silence_threshold how is this called in gradio?

**Comment by jhj0517** [comment]
@viebrix Parameters are cherry-picked to include only those common to different Whisper implementations (e.g., faster-whisper, insanely-fast-whisper).
I've moved the issue to #199!
