### ISSUE TITLE
Option for Output File to be named the same as Input Video

### ISSUE THREAD

**Issue by Juiin** [jhj0517/Whisper-WebUI#20]
If the Subtitle and the Video File have the same name, most video players automatically detect it as a subtitle for the video. Would be convenient to have an option for the Output subtitle file to automatically be given the exact same name as the video file used to generate the subtitles.

**Comment by jhj0517** [comment]
Hi @Juiin , sorry for late response. 
This was resolved in #29, so I'm closing!
