### ISSUE TITLE
MacOS Ver.Whisper-WebUI-Mac.zip install.sh needed to convert to Unix format

### ISSUE THREAD

**Issue by Linrop** [jhj0517/Whisper-WebUI#202]
Its seemed the MacOS ver. install.sh included CRLF line terminators cannot run directly. Need dos2unix.

**Comment by jhj0517** [comment]
Thanks for reporting this.
 I've just run dos2unix on Git Bash and updated the zip file. Can you check if you can run the shell script now? 

https://github.com/jhj0517/Whisper-WebUI/releases/tag/v1.0.0

**Comment by joshuachough** [comment]
I also had this problem, thanks for the fix!

**Comment by jhj0517** [comment]
I just updated the zip file in the my really old Mac device. 

https://github.com/jhj0517/Whisper-WebUI/releases/tag/v1.0.0

It should work now. Please feel free to re-open if anyone still face the issue!
