### ISSUE TITLE
How do I apply fine-tuned models?

### ISSUE THREAD

**Issue by dlwwlakfwk2** [jhj0517/Whisper-WebUI#222]
https://huggingface.co/sin2piusc/whisper-large-v2-anime

Here, I replicated the fine-tuning model to a local folder.

Now how do I apply this model to this Whisper-WebUI?

**Comment by jhj0517** [comment]
Hi @dlwwlakfwk2. Thanks for raising the issue.
Currently, the fine-tuned model is only supported for the `faster-whisper` implementation (you can use the model by simply putting it in `models/faster-whisper`). 
but it should work on other implementations as well.

I'm looking into it!

**Comment by jhj0517** [comment]
The model from the link you've posted uses `transformer` to inference.
So to run the model it needs migration from `openai-whipser` package to `transformer`.

If you want to run the model until I do something about it, you can see the [inference script](https://huggingface.co/clu-ling/whisper-large-v2-japanese-5k-steps#transcription).

**Comment by jhj0517** [comment]
@ephao Hi, it should work if you placed with the sub directory name,
This is example folder structure for `faster-whisper-large-v3-turbo-ct2`:
![image](https://github.com/user-attachments/assets/9cc837b8-48c3-4dd3-b94c-d654344f2771)

Doesn't it work with this way?

**Comment by ephao** [comment]
Hi jhj, thanks for answering. I just put it like this.
<img width="701" alt="image" src="https://github.com/user-attachments/assets/140c8c21-e0ee-42b6-a502-2145b69566b7">
The model shows in the GUI, but it can't work. Just like this
![image](https://github.com/user-attachments/assets/1852b3a3-15d8-490b-8f4a-5ae7ef495812)

**Comment by jhj0517** [comment]
Ah OK, the model structure is not `faster-whisper`'s, but the `transformer`'s, which is the same as `insanely_fast_whisper`.

But I have not implemented custom model paths for `insanely_fast_whisper` yet, I will work on it soon!

Until then, custom model paths are only possible for `faster-whisper`, such as:
- https://huggingface.co/arc-r/faster-whisper-large-zh-cv11
- https://huggingface.co/littlevincee/faster-whisper-chinese

**Comment by jhj0517** [comment]
@ephao @dlwwlakfwk2 

Fine-tuned models with `insanely_fast_whisper` is enabled in #378.
The model links you posted are the same with `insanely_fast_whisper`, so you need to explicitly specify the implementation to use it:

```
python app.py --whisper_type insanely_fast_whisper
```

Closing since this is solved, feel free to re open if you still have any problem!
