### ISSUE TITLE
Offline translation does not work

### ISSUE THREAD

**Issue by Bigbigliar** [jhj0517/Whisper-WebUI#229]
Windows 10

I already had Whisper installed before and everything worked without an Internet connection, but when I just installed it using Automatic Installation and when I try to translate, I get the following error (when the Internet is connected, everything works)

Initializing NLLB Model..

Error: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /facebook/nllb-200-1.3B/resolve/main/model.safetensors (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000012FFCA843A0>: Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 436719b9-5dc1-4cf9-8775-496ce4dd514a)')
Traceback (most recent call last):
  File "D:\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "D:\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1856, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1634, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "D:\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1610, in validate_outputs
    raise ValueError(
ValueError: An event handler (translate_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x0000012FF6220F10>, <gradio.templates.Files object at 0x0000012FF6221030>]
Received outputs:
    [None]

**Comment by Bigbigliar** [comment]
Фfter the update everything works correctly. I didn't notice any other problems offline, the only thing I get is this message, "You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset". It seems like a long time ago that there was no such thing, but there must be some other reason for this.
Thanks for the fix.
P.S.
The translated subtitle file does not appear in the \outputs\translations folder, it replaces the original subtitle file in the \outputs folder

**Comment by jhj0517** [comment]
>The translated subtitle file does not appear in the \outputs\translations folder

@Bigbigliar Thanks for pointing this out. 
It's fixed in #231. 

Please let me know if you run into any problems, and feel free to reopen!
