### ISSUE TITLE
No event data

### ISSUE THREAD

**Issue by ARaOnn** [jhj0517/Whisper-WebUI#23]
I follow the guide to install and convert video or subtitle files, after that I got an error.

Can you tell me how to fix it?

Task exception was never retrieved
future: <Task finished name='93dp2rexo86_0' coro=<Queue.process_events() done, defined at D:\project\subtitle2\Whisper-WebUI\venv\lib\site-packages\gradio\queueing.py:329> exception=AssertionError('No event data')>
Traceback (most recent call last):
  File "D:\project\subtitle2\Whisper-WebUI\venv\lib\site-packages\gradio\queueing.py", line 343, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "D:\project\subtitle2\Whisper-WebUI\venv\lib\site-packages\gradio\queueing.py", line 303, in call_prediction
    assert data is not None, "No event data"
AssertionError: No event data

**Comment by aleksay85** [comment]
Having a same problem I am assuming this is a bug that's not been fixed :P.

**Comment by jhj0517** [comment]
Hi @ARaOnn , @aleksay85 .
It seems like bug from old version of gradio. 
So I've fixed in #24, can you remove old project folder and test again?

**Comment by ARaOnn** [comment]
Hi @jhj0517 
It works well. Everything is wokring now 
thx
