### ISSUE TITLE
word repeat issue

### ISSUE THREAD

**Issue by snowyegret23** [jhj0517/Whisper-WebUI#238]
**Which OS are you using?**
 - OS: Windows10 x64, Python 3.10.8, CUDA 12.1

Large-3 모델 및 기타 Larg 모델들을 사용 시 단어 반복 이슈가 있습니다.

- 18분정도 되는 일본어 음성을 Transcript시 중간에 아래와 같은 반복되는 부분이 나옵니다.
```
45
00:02:20,200 --> 00:02:50,200
え、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ、あ
```
```
67
00:04:33,899 --> 00:04:34,899
はーい、リュウジョウお兄ちゃんとタイガちゃんが産まれました。

68
00:04:34,899 --> 00:04:35,899
はーい、リュウジョウお兄ちゃんとタイガちゃんが産まれました。

69
00:04:35,900 --> 00:04:36,900
はーい、リュウジョウお兄ちゃんとタイガちゃんが産まれました。

70
00:04:36,900 --> 00:04:37,900
はーい、リュウジョウお兄ちゃんとタイガちゃんが産まれました。

71
00:04:37,900 --> 00:04:38,900
はーい、リュウジョウお兄ちゃんとタイガちゃんが産まれました。

72
00:04:38,900 --> 00:04:39,900
はーい、リュウジョウお兄ちゃんとタイガちゃんが産まれました。
```

- 1시간 1분정도 되는 일상 한국어 대화를 Transcript 시 Large모델별로 다음과 같은 결과가 파일 끝까지 반복됨
```
104
00:06:38,000 --> 00:06:40,000
웃음소리

105
00:06:52,000 --> 00:06:54,000
웃음소리

106
00:06:58,000 --> 00:07:00,000
웃음소리

107
00:07:00,000 --> 00:07:02,000
웃음소리

108
00:07:02,000 --> 00:07:04,000
웃음소리

109
00:07:04,000 --> 00:07:06,000
웃음소리

110
00:07:06,000 --> 00:07:08,000
웃음소리
```

```
69
00:04:08,000 --> 00:04:10,000
오오오

70
00:04:10,000 --> 00:04:12,000
오오오

71
00:04:12,000 --> 00:04:14,000
오오오

72
00:04:14,000 --> 00:04:16,000
오오오

73
00:04:16,000 --> 00:04:18,000
오오오

74
00:04:18,000 --> 00:04:20,000
오오오

75
00:04:20,000 --> 00:04:22,000
오오오
```

```
64
00:02:36,000 --> 00:02:38,000
오 오 오 오 오 오 오

65
00:02:38,000 --> 00:02:40,000
오 오 오 오 오 오

66
00:02:40,000 --> 00:02:42,000
오 오 오 오 오 오

67
00:02:42,000 --> 00:02:44,000
오 오 오 오 오 오

68
00:02:44,000 --> 00:02:46,000
오 오 오 오 오 오
```

한국어 음성본은 첨부가 불가하지만, 일본어 음성은 아래 링크에서 받아보실 수 있습니다.
https://pixeldrain.com/u/LKGzDNt1

관련된 이슈는 다음과 같은 듯 합니다.
- https://github.com/openai/whisper/discussions/1059
- https://github.com/openai/whisper/discussions/112

**Comment by jhj0517** [comment]
@snowyegret23 님 안녕하세요. Whisper 모델에서 비교적 자주 발생하는 할루시네이션인데요, 

주로 음성에 말 소리 이외의 소음이 들어있거나 배경음악이 있을 때 발생합니다.
올려주신 샘플에도 배경음악과 소음이 들어있네요.

이러한 할루시네이션을 줄이기 위한 지금까지의 그나마 최선의 방법은 VAD 를 이용하는 것인데요, 
VAD 옵션에서 `Minimum Silence Duration (ms)` 를 약간 줄이고 VAD를 활성화 시키고나면, 사람의 말소리가 아니라고 판단되는 부분을 완전히 잘라내는 방식으로 전처리하기 때문에 이러한 할루시네이션을 약간이나마 줄일 수 있습니다.

또한 저와 다른 많은 분들의 경험에 의하면 `large-v3` 모델이 `large-v2` 모델 보다 더 자주 할루시네이션을 발생시켰습니다. ( #152 )

생각해보니 [Sepformer](https://huggingface.co/speechbrain/sepformer-wham) 같은 모델을 활용해서 배경음악을 분리하는 전처리 과정을 추가하면 이러한 할루시네이션을 줄이는데 도움이 될 것 같습니다.

**Comment by jhj0517** [comment]
8168488cfa668dc53f2af4a56f5949e97e874ad4 에서 배경 음악 분리 전처리 과정 추가를 TODO 리스트에 추가하였습니다.

**Comment by snowyegret23** [comment]
Temperature를 좀 높힌 후, 말씀하신 사항들을 적용하니 정확도가 떨어지나 할루시네이션 현상의 빈도가 줄었네요. 감사합니다!
한국어는 위 방법 적용시 아예 다른 소리를 해서 적용이 힘들 것 같습니다.
도움 주셔서 감사합니다!
