### ISSUE TITLE
Error Connection errored out

### ISSUE THREAD

**Issue by mucobulut** [jhj0517/Whisper-WebUI#246]
Hello. 
I have been using your AI tool for one year; thank you so much. It is very useful.
But I am taking an error message. I cannot use it for 2 months.
I am taking this error: "Connection errored out."

I am using Windows 10. And I am using Whisper-WebUI on Pinokio.

Help me with this problem, please.
Thanks for taking time!

![error](https://github.com/user-attachments/assets/20ef88a6-fa22-422c-b917-e6b041fc9fd1)

**Comment by jhj0517** [comment]
This is because of an older version of `gradio`, it should now work fine if you reinstall the app in pinokio.

Closing this thread, please feel free to re-open it if you encounter the same bug!
