### ISSUE TITLE
UpdateBat파일경로 수정

### ISSUE THREAD

**Issue by SeongGyu1216** [jhj0517/Whisper-WebUI#251]
혹시 update.bat파일을 같은 폴더안에 넣어도 작동되게할 수 있을까요?

예를들어 E:\Whisper  이렇게 사용하고있는데 
update.bat파일을 E:\Whisper  위치에 두고
E:\Whisper\Whisper-WebUI 에 파일들을 둬야하더라구요. 
 E:\Whisper  이 폴더안에 모든 파일들을 두고싶어요! 가능할까요?

**Comment by jhj0517** [comment]
안녕하세요. 

`update.bat` 에서 `-C` 옵션을 모두 제거하신 후 폴더 내부에 배치하실 수 있습니다.

수정 후 예시)
```
@echo off
git pull origin master 2>NUL
if %ERRORLEVEL% == 0 (
    goto :done
) else (
    git reset --hard
    git pull origin master
    goto :done
)

:done
echo Successfully updated WebUI.
pause
```

**Comment by SeongGyu1216** [comment]
@echo off
git  "%~dp0" pull origin master 2>NUL
if %ERRORLEVEL% == 0 (
    goto :done
) else (
    git  "%~dp0" reset --hard
    git  "%~dp0" pull origin master
    goto :done
)

:done
echo Successfully updated WebUI.
pause

이렇게하니


git: 'E:\Whisper" reset --hard' is not a git command. See 'git --help'.
git: 'E:\Whisper" pull origin master' is not a git command. See 'git --help'.
Successfully updated WebUI.
계속하려면 아무 키나 누르십시오 . . .


위 처럼 경로가 대충은 잡히는 것 같긴합니다만  안됩니다 ㅠ

**Comment by jhj0517** [comment]
Whisper-WebUI 안의 모든 파일들 (`.git` 폴더 포함) 을 밖으로 꺼내시면 됩니다.
단 이렇게 하면 `venv` 폴더의 경로가 달라지므로 venv 폴더 삭제 후 [install.bat](https://github.com/jhj0517/Whisper-WebUI/blob/master/Install.bat)을 다시 실행하셔야 합니다.

**Comment by SeongGyu1216** [comment]
파일들이 너무 중구난방해질 것 같아서 그냥 정석적인 방법으로 해야겠습니다. 번거롭게해서 죄송합니다.
