### ISSUE TITLE
cudnn_cnn_infer64_8.dll error

### ISSUE THREAD

**Issue by SeongGyu1216** [jhj0517/Whisper-WebUI#253]
OS : Window 11

Use "faster-whisper" implementation
Device "cuda" is detected
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Could not locate cudnn_cnn_infer64_8.dll. Please make sure it is in your library path!
"launching the app"
계속하려면 아무 키나 누르십시오 . . .

**Comment by SeongGyu1216** [comment]
어찌저찌 다른 경로에있는 파일을 옮겼는데


Could not locate cublasLt64_11.dll. Please make sure it is in your library path!


이러한 다른 버전의 오류가 뜨네요..

**Comment by jhj0517** [comment]
안녕하세요. 사용 중인 `CUDA` & `cuDNN` 버전이 무엇인가요?

대부분의 비슷한 종류의 에러 (#114 , #235 ) 는 CUDA 와 cuDNN 을 통째로 버전 호환성에 맞게 재설치 하는 것으로 해결할 수 있습니다.

이 WebUI 에서 권장되는 `CUDA` & `cuDNN` 사양은

- [`CUDA 12.4`](https://developer.nvidia.com/cuda-12-4-0-download-archive)
- [`cuDNN 9.3.0`](https://developer.nvidia.com/cudnn-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_network)

입니다.

버전 호환성 참조 : https://docs.nvidia.com/deeplearning/cudnn/latest/reference/support-matrix.html

**Comment by SeongGyu1216** [comment]
Use "faster-whisper" implementation
Device "cuda" is detected
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!
"launching the app"
계속하려면 아무 키나 누르십시오 . . .


삭제 후 저 버전 설치해봤는데도 안되네요...

**Comment by SeongGyu1216** [comment]
Traceback (most recent call last):
  File "E:\Whisper-WebUI\app.py", line 5, in <module>
    from modules.whisper.whisper_factory import WhisperFactory
  File "E:\Whisper-WebUI\modules\whisper\whisper_factory.py", line 4, in <module>
    from modules.whisper.faster_whisper_inference import FasterWhisperInference
  File "E:\Whisper-WebUI\modules\whisper\faster_whisper_inference.py", line 4, in <module>
    import torch
  File "E:\Whisper-WebUI\venv\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 지정된 모듈을 찾을 수 없습니다. Error loading "E:\Whisper-WebUI\venv\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
"launching the app"
계속하려면 아무 키나 누르십시오 . . .

아예 whisperwebui폴더 삭제하고 다시다운받고 install 누르고 완료 상태 뜬다음 실행눌렀는데 저리뜨네요.

Git 설치, ffmpeg bin폴더 환경변수 추가, Cuda 설치파일 2개, python 3.10.6설치 (환경변수 추가체크함), 
E드라이브 폴더에 빈공간 우클릭 - git 클론 설치 주소 엔터 - Whisper webui 폴더생성됨 - Install.bat 쭉 기다려서 설치완료 상태 확인 (계속하려면 아무 키나 누르십시오 문구도 확인) Start-webui.bat 실행 (user start webui.bat도 실행해봄) 
결과 오류 ㅠㅠㅠ

제가 설치 방법을 잘못한 것일까요? 유튜브 보면서해봤는데 안되더라구요

**Comment by SeongGyu1216** [comment]
https://github.com/jhj0517/Whisper-WebUI/issues/235
https://github.com/Purfview/whisper-standalone-win/releases
위 해결방법으로 해결했습니다!

이렇게 수동으로 안 해도 될 텐데 왜 이렇게 해야하는지 모르겠네요 옛날엔 안 그랬었는데 포멧 하고나서 그런 것 같아요

**Comment by megapro17** [comment]
I also have this error
I've switched to insanely-fast-whisper which works fine

**Comment by jhj0517** [comment]
I think this is `cuDNN` & `CUDA` version incompatibility issues, but difficult to reproduce. 
If anyone knows the condition to reproduce this, please let me know

**Comment by megapro17** [comment]
> If anyone knows the condition to reproduce this, please let me know

I just installed the latest version from the scratch and got it

**Comment by jhj0517** [comment]
Currently recommended solution for this is 

[Perfview's solution](https://github.com/Purfview/whisper-standalone-win/releases/tag/libs), which is to manually put the dll files corresponding to your CUDA version into the system32 folder.

**Comment by jhj0517** [comment]
duplicate with #271, if anyone faced the same error refer to https://github.com/jhj0517/Whisper-WebUI/issues/271#issuecomment-2350820352
