### ISSUE TITLE
Bug while using whisper ai through colab

### ISSUE THREAD

**Issue by joonseo0505** [jhj0517/Whisper-WebUI#260]
**Which OS are you using?**
 - OS: Colab

Below is code in "Installation" part of colab document.

#@title #Installation
#@markdown This cell will install dependencies for Whisper-WebUI!
!git clone https://github.com/jhj0517/Whisper-WebUI.git
%cd Whisper-WebUI
!pip install git+https://github.com/jhj0517/jhj0517-whisper.git
!pip install faster-whisper==1.0.3
!pip install gradio==4.29.0
# Temporal bug fix from https://github.com/jhj0517/Whisper-WebUI/issues/220
!pip install pytubefix
!pip install tokenizers==0.19.1
!pip install pyannote.audio==3.3.1

since the gradio version is changed, you have to fix 
!pip install gradio==4.29.0 -> !pip install gradio==4.43.0
to use it correctly in Colab

**Comment by jhj0517** [comment]
Thanks for noticing! 
Fixed in #261
