### ISSUE TITLE
repeated words, non-English language 

### ISSUE THREAD

**Issue by violetgoing** [jhj0517/Whisper-WebUI#268]
Help me please, what should I turn on so that the words do not repeat? I tried to turn on VAD, language Russian 52 minutes

**Comment by violetgoing** [comment]
Pls help, idk what to do, If i do vad too high and the quality is lost, if too low and the words are repeated

**Comment by violetgoing** [comment]
No, there's just louder and louder voices.

**Comment by violetgoing** [comment]
No, there are louder and quieter voices.

**Comment by violetgoing** [comment]
There's also extraneous noises like wind.

**Comment by violetgoing** [comment]
By the way, why can't I select a model from my computer? Like #Const-me/Whisper

**Comment by jhj0517** [comment]
> extraneous noises

This is a whisper hallucination that happens when there's background music or noise in the audio. 
I'm closing this because this is the same as #152, please continue there!

> By the way, why can't I select a model from my computer?

I don't understand what you mean, but if you want to use custom model (like [faster-whisper-large-v2-japanese-5k-steps](https://huggingface.co/zh-plus/faster-whisper-large-v2-japanese-5k-steps/tree/main)) then you can put any faster-whisper model into `WebUI-Path\models\Whisper\faster-whisper` directory and use it.

**Comment by violetgoing** [comment]
can i install [this](https://huggingface.co/bzikst/faster-whisper-large-v3-russian-int8)? it large-v3 but in `WebUI-Path\models\Whisper\faster-whisper` i have only large-v1

**Comment by violetgoing** [comment]
@jhj0517

**Comment by jhj0517** [comment]
Yes, if you manually download the model and place it into the `WebUI-Path\models\Whisper\faster-whisper`,
It should work fine. Let me know if you encounter any errors

**Comment by violetgoing** [comment]
step 1
![image](https://github.com/user-attachments/assets/be92dca7-1fc5-4ce3-9560-fe9f52b6cac8)
step 2
![image](https://github.com/user-attachments/assets/a91894a8-a905-4684-8bf9-c93119dd2425)

**Comment by violetgoing** [comment]
@jhj0517

**Comment by jhj0517** [comment]
This is related to #253 and I think it's a `cuDNN` & `CUDA` & `torch` version incompatibility problem.

You have some options to resolve this:

1. If you're using `CUDA` versions other than 12.4, install 12.4.
2. Remove the `venv` directory and run `install.bat` again.

3. If you still face the error, follow [Perfview's solution](https://github.com/Purfview/whisper-standalone-win/releases/tag/libs)

Or alternatively, if you're finding these cumbersome, use Docker for the application.
You can see [Running with Docker](https://github.com/jhj0517/Whisper-WebUI?tab=readme-ov-file#running-with-docker) guide.
( You will need to install and run docker-desktop first.)
