### ISSUE TITLE
Timings are off on the first few lines

### ISSUE THREAD

**Issue by JeremyMahieu** [jhj0517/Whisper-WebUI#27]
On the first few lines it seems to rapidly put some of the lines, then hold one line for 30 seconds, after that everything is normal. Notice that these lines happen exactly on the second, which makes it already indicate that it's a bug.

Example:
```
1
00:00:00,000 --> 00:00:01,000
 Okay.

2
00:00:01,000 --> 00:00:02,000
 Delete a flight plan.

3
00:00:02,000 --> 00:00:03,000
 Autopilot off.

4
00:00:03,000 --> 00:00:04,000
 Altitude 3000.

5
00:00:04,000 --> 00:00:05,000
 Okay.

6
00:00:05,000 --> 00:00:32,500
 Contact surface until aboard.

7
00:00:32,500 --> 00:00:38,500
 ♪♪

8
00:00:38,500 --> 00:00:41,039
 -♪♪

9
00:00:41,039 --> 00:00:43,079
 Who is that?
```

**Which OS are you using?**
 - OS: Windows 11

**Comment by jhj0517** [comment]
Hi @JeremyMahieu .
Is there any noise or singing in the file?
Then it might sometimes have a very inaccurate timestamp, like this. (which I've also experienced sometimes).

And from what I've found, using audio files over video files gives better results.

Like #28, it seems to be a problem with the Whisper model itself, not with my Web UI.
So I'll close this soon!

**Comment by JeremyMahieu** [comment]
Yeah exactly. This was with an mkv file and using an extrackted audio track gives slightly different timings, but both are innacurate for the first few lines.
The audio starts with some lines and then an intro sequence with music.
