### ISSUE TITLE
Couldn't find Cuda Dll

### ISSUE THREAD

**Issue by bigfordy1983** [jhj0517/Whisper-WebUI#271]
**Which OS are you using?**
 - OS: Windows 11 , Python 3.11.9

Cmd Log is thus:

Use "faster-whisper" implementation
Device "cuda" is detected
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!
"launching the app"

Suspect it isn't detecting CUDA. It is installed.

**Comment by jhj0517** [comment]
Same with #253, I think it's a `cuDNN` & `CUDA` & `torch` version Incompatibility problem.

Can you check CUDA & torch version that you're using?
```
python -c "import torch; print(f'torch: {torch.__version__}'); print(f'CUDA: {torch.version.cuda}')"
```

The project uses CUDA 12.4 by default. If it says
```
torch: 2.4.1+cu124
CUDA: 12.4
```
And you're still having the problem, 

The recommended solution is [Perfview's solution](https://github.com/Purfview/whisper-standalone-win/releases/tag/libs), which is to manually put the dll files corresponding to your CUDA version into the system32 folder.

**Comment by paolodalprato** [comment]
Same isssue here, Perfview's solution fixed well

**Comment by mark-wd** [comment]
Same issue. Also fixed with Perfview's solution.

**Comment by Tom-Neverwinter** [comment]
current version doesn't even have: cudnn_ops_infer64_8.dll 
have to add as an extra.


cudnn_9.4.0_windows.exe

temp installs to:
C:\Users\user\AppData\Local\Temp\cudnn

cudnn for 11,8/12.6: cudnn_ops64_9.dll

**Comment by jhj0517** [comment]
Closing with https://github.com/jhj0517/Whisper-WebUI/pull/345,
Feel free to re-open if you face same issue.
