### ISSUE TITLE
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by martindellavecchia** [jhj0517/Whisper-WebUI#294]
where should I put this library?

~/docker/Whisper-WebUI$ ./start-webui.sh --server_name 0.0.0.0
Use "faster-whisper" implementation
Device "cuda" is detected
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
config.json: 100%|███████████████████████████████████████████████| 2.80k/2.80k [00:00<00:00, 3.01MB/s]
vocabulary.txt: 100%|██████████████████████████████████████████████| 460k/460k [00:00<00:00, 1.38MB/s]
tokenizer.json: 100%|████████████████████████████████████████████| 2.20M/2.20M [00:00<00:00, 3.71MB/s]model.bin: 100%|█████████████████████████████████████████████████| 3.09G/3.09G [00:55<00:00, 55.2MB/s]
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
./start-webui.sh: línea 4:  6516 Abortado                (`core' generado) python3.10 app.py "$@"
launching the app

**Comment by jhj0517** [comment]
I'm closing this as well, since I understand it was resolved in #293. 

Feel free to reopen if you find any bugs!

**Comment by jhj0517** [comment]
duplicate with #271, if anyone faced the same error refer to https://github.com/jhj0517/Whisper-WebUI/issues/271#issuecomment-2350820352
