### ISSUE TITLE
Question: Where are my mp4, mkv, mp3 files after uploading them to be transcribed.

### ISSUE THREAD

**Issue by martindellavecchia** [jhj0517/Whisper-WebUI#297]
Ubuntu 24.04
Running it with ./start-webui.sh

I was wondering: right after I upload a video o audio file, were is it, so I can access it later on.
Assuming this is a 100% offline & local process, the files should be on my linux box.

Thanks.

**Comment by jhj0517** [comment]
You mean where `gradio` caches the files when you upload files with `gr.Files()`?

It would be the default temp directory for your OS.
For example it would be `C:\\Users\\%USER%\\AppData\\Local\\Temp\\gradio`, 

For Ubuntu it could be `/tmp/gradio` or `/var/tmp/gradio`.

**Comment by martindellavecchia** [comment]
Super, thanks.
