### ISSUE TITLE
feature request - Translate into different languages

### ISSUE THREAD

**Issue by Tobe2d** [jhj0517/Whisper-WebUI#3]
I tested the project today and it is working really nicly. and I just though would be really usefull if you can add translate into different languages like a small drop down menu next to "Translate to English?"

**Comment by jhj0517** [comment]
Hello, Thank you for your suggestion.

I was actually considering adding a T2T (Text-to-Text) translation feature as well.
The current "Translate to English?" option is a Speech-to-Text English translation feature provided by the Whisper model (for large models only). It translates speech directly to English text end-to-end.

Personally, I'm thinking of using the DeepL API, as it has been the best performer for translating several languages in my personal experience. 

Using a Facebook's NLLB model is also good option. (but In my experience with `NLLB-200-1.3B` , it doesn't perform very well...)

Anyway, there have been requests for a translation feature, so I'm working on it.

**Comment by Tobe2d** [comment]
I hope the solution you will implement will include  Semitic languages such as Hebrew, Arabic and other european languages.

**Comment by jhj0517** [comment]
This is resolved with #82
