### ISSUE TITLE
how to enable diarization

### ISSUE THREAD

**Issue by violetgoing** [jhj0517/Whisper-WebUI#302]
**Which OS are you using?**
 - OS: Windows
How do I enable diarization? I seem to have enabled it, I agreed on `https://huggingface.co/pyannote/speaker-diarization-3.1`, I entered the token but I get this error, maybe I entered the token wrong?
![image](https://github.com/user-attachments/assets/4593046b-4aa9-4b0f-ab23-3a52f1a04245)

**Comment by jhj0517** [comment]
Hello, have you agreed to the TOS of both models?

- https://huggingface.co/pyannote/speaker-diarization-3.1
- https://huggingface.co/pyannote/segmentation-3.0

**Comment by violetgoing** [comment]
@jhj0517 yes, i click to this button
![image](https://github.com/user-attachments/assets/90b71b5b-5366-4cdc-958c-8b8818bccc20)
but have this
![image](https://github.com/user-attachments/assets/a5e67c81-e1b9-4761-88c4-ae00d3be2137)

**Comment by dng-nguyn** [comment]
You need to manually assign permissions for accessing the repos in the api key details

**Comment by jhj0517** [comment]
For your information, you can simply select "READ" type token when you create a token in huggingface. 
READ type is enough to access the model.

![image](https://github.com/user-attachments/assets/1af45ba9-c2f9-4bfd-a712-297597dbbd1b)

**Comment by violetgoing** [comment]
Ohhhh thank you all, you've been very helpful
