### ISSUE TITLE
Dependencies need to be fixed

### ISSUE THREAD

**Issue by Kozmosa** [jhj0517/Whisper-WebUI#317]
OS: Ubuntu 24.04 noble(on the Windows Subsystem for Linux)

When executing the install.sh, which actually performed a *pip install -r reguirements.txt* command, it turned out an error with pip.

gradio 4.43.0 requires fastapi<0.113.0, but you have fastapi 0.114.1 which is incompatible.
vllm 0.6.2 requires transformers>=4.45.0, but you have transformers 4.42.3 which is incompatible

which indicated that there are corrupted dependencies.

Given that circumstance, l tried just install latest versions of gradio, vllm, fastapi, transformers, and it worked by now

Hopefully, corrupted dependencies could be fixed.

**Comment by jhj0517** [comment]
I'm closing this assuming this is no longer reproducible.

Feel free to reopen it if anyone has the same problem.
