### ISSUE TITLE
Save Settings

### ISSUE THREAD

**Issue by viebrix** [jhj0517/Whisper-WebUI#320]
Thanks(!!!) for implementing the VAD section and all the properties you added. Now with fine-tuning all these settings, GERMAN subtitles from tv series works great. Sometimes there are some curious mistakes, like uppercase and wrong spelled words. This was not the case with previous whisper models, but on the whole it works well.
But every time I have to restart firefox, I have to re enter all those settings. Is there any possibility to save the whole settings (exclude the Uploaded File). This would an easement for working with your excellent tool.

**Comment by jhj0517** [comment]
Hi @viebrix ! If you're using the latest version of the WebUI,
all parameters are automatically cached in [default_parameters.yaml](https://github.com/jhj0517/Whisper-WebUI/blob/master/configs/default_parameters.yaml) and loaded on startup.

Resolved in #42, so updating the WebUI to the latest version will solve ths.

**Comment by viebrix** [comment]
Perfect - Thanks a lot!
