### ISSUE TITLE
insanely_fast_whisper generation failes

### ISSUE THREAD

**Issue by PARKasd** [jhj0517/Whisper-WebUI#321]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]
Windows 11
cuda 12.1
![image](https://github.com/user-attachments/assets/6f67d0f0-3ae9-47d2-96ef-003aa3b6a172)

getting this type of error when using insanely fast whisper in newest version of this repo. idk why I'm facing this bug

**Comment by PARKasd** [comment]
I think its duplicated
[#226](https://github.com/jhj0517/Whisper-WebUI/issues/226#issuecomment-2272744299)

**Comment by PARKasd** [comment]
By reinstalling transformers with #226, It works as exptected.

**Comment by jhj0517** [comment]
I'm closing this assuming it's no longer reproducible!
