### ISSUE TITLE
the new model

### ISSUE THREAD

**Issue by Mikhail195** [jhj0517/Whisper-WebUI#329]
hi 

Is it possible to add your own model, for example this one https://huggingface.co/antony66/whisper-large-v3-russian?

**Comment by jhj0517** [comment]
Hi. If the model is trained on faster-whisper then it should work if you place the model files (including metadata files) in the `Whisper-WebUI\models\Whisper\faster-whisper`.

This is an example directory structure for the `faster-whisper-large-v3-turbo-ct2` :

![image](https://github.com/user-attachments/assets/ce861c12-6fdc-48d4-b327-07db193318b8)

**Comment by jhj0517** [comment]
Closing since this is duplicated with https://github.com/jhj0517/Whisper-WebUI/issues/309,
Feel free to re-open!
