### ISSUE TITLE
Add segmentation-3.0 information to info in speaker diarization part of WebUI

### ISSUE THREAD

**Issue by skaghzz** [jhj0517/Whisper-WebUI#333]
https://github.com/jhj0517/Whisper-WebUI/blob/6ae85bdc02316106307f256ee178d849eedc0da9/app.py#L170-L174

Follow [readme.md](https://github.com/jhj0517/Whisper-WebUI?tab=readme-ov-file#feature). Use of the model is also required for segmentation-3.0.

> This is only needed the first time you download the model. If you already have models, you don't need to enter. To download the model, you must manually go to "https://huggingface.co/pyannote/speaker-diarization-3.1" and "https://huggingface.co/pyannote/segmentation-3.0" and agree to their requirement.

**Comment by jhj0517** [comment]
Hi. Thanks for raising the issue. 
It might be confusing and better to update the instructions.

I have updated the info in #334, please feel free to reopen if you have any suggestions!
