### ISSUE TITLE
File upload error in T2T translation

### ISSUE THREAD

**Issue by scarnago** [jhj0517/Whisper-WebUI#339]
**Which OS are you using?**
 - OS: Windows 11
 
 When I try to use the T2T translation i'm getting this error I have validated i'm using a valid srt file

```
error
"Invalid file type. Please upload a file that is one of these formats: ['.vtt', '.srt']"
``` 

How I can fix this error?

**Comment by OneSteelTank** [comment]
#335

**Comment by jhj0517** [comment]
Duplicate #335, this will be fixed when you update the web ui. 
Feel free to reopen if the problem persists!
