### ISSUE TITLE
No module named 'gradio_i18n' on google colab

### ISSUE THREAD

**Issue by joonseo0505** [jhj0517/Whisper-WebUI#342]
**Which OS are you using?**
Google Colab

On Run status, im getting error message

File "/content/Whisper-WebUI/Whisper-WebUI/app.py", line 4, in <module>
    from gradio_i18n import Translate, gettext as _
ModuleNotFoundError: No module named 'gradio_i18n'

**Comment by jhj0517** [comment]
@joonseo0505 Ah, thanks for noticing me!
This was fixed in #343 and worked fine. 

Please let me know if the problem persists!

**Comment by joonseo0505** [comment]
Thank you for the quick action! But last month [update gradio to 4.43.0] -> [merge pool request] had a similar issue, so I forked this repository for that commit and tried to run it today, but there was an error "No module named 'whisper'" just didn't work either. Is there a way to run 100% on the previous commit/fork?

**Comment by jhj0517** [comment]
Closing asumming this is resolved, 
Feel free to reopen it!
