### ISSUE TITLE
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

### ISSUE THREAD

**Issue by gerberanub** [jhj0517/Whisper-WebUI#344]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]
windows 11

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

torchmetrics 1.5.0 requires numpy<2.0,>1.20.0, but you'll have numpy 2.0.2 which is incompatible.
pytorch-metric-learning 2.6.0 requires numpy<2.0, but you'll have numpy 2.0.2 which is incompatible.
torchvision 0.20.0+cu121 requires torch==2.5.0+cu121, but you'll have torch 2.3.1+cu121 which is incompatible.
Successfully installed Mako-1.3.6 absl-py-2.1.0 aiofiles-23.2.1 alembic-1.13.3 annotated-types-0.7.0 antlr4-python3-runtime-4.9.3 anyio-4.6.2.post1 asteroid-filterbanks-0.4.0 attrs-24.2.0 audeer-2.2.0 audiofile-1.5.0 audioread-3.0.1 audmath-1.4.1 av-12.3.0 certifi-2024.8.30 cffi-1.17.1 charset-normalizer-3.4.0 click-8.1.7 cloudpickle-3.1.0 colorama-0.4.6 coloredlogs-15.0.1 colorlog-6.8.2 contextlib2-21.6.0 contourpy-1.3.0 ctranslate2-4.4.0 cycler-0.12.1 decorator-5.1.1 docopt-0.6.2 dora-search-0.1.12 einops-0.8.0 exceptiongroup-1.2.2 fastapi-0.115.2 faster-whisper-1.0.3 ffmpeg-python-0.2.0 ffmpy-0.4.0 filelock-3.16.1 flake8-7.1.1 flatbuffers-24.3.25 fonttools-4.54.1 fsspec-2024.10.0 future-1.0.0 gradio-4.44.1 gradio-client-1.3.0 gradio-i18n-0.1.0 greenlet-3.1.1 h11-0.14.0 httpcore-1.0.6 httpx-0.27.2 huggingface-hub-0.26.1 humanfriendly-10.0 hydra-colorlog-1.2.0 hydra-core-1.3.2 hyperpyyaml-1.2.2 idna-3.10 importlib-resources-6.4.5 iniconfig-2.0.0 intel-openmp-2021.4.0 jinja2-3.1.4 joblib-1.4.2 jsonschema-4.23.0 jsonschema-specifications-2024.10.1 julius-0.2.7 kiwisolver-1.4.7 lameenc-1.7.0 lazy-loader-0.4 librosa-0.10.2.post1 lightning-2.4.0 lightning-utilities-0.11.8 llvmlite-0.43.0 markdown-it-py-3.0.0 markupsafe-2.1.5 matplotlib-3.9.2 mccabe-0.7.0 mdurl-0.1.2 mkl-2021.4.0 ml-collections-0.1.1 more-itertools-10.5.0 mpmath-1.3.0 msgpack-1.1.0 musdb-0.4.2 museval-0.4.1 mypy-1.12.1 mypy-extensions-1.0.0 networkx-3.2.1 numba-0.60.0 numpy-2.0.2 omegaconf-2.3.0 onnx-1.17.0 onnx2pytorch-0.5.0 onnxruntime-1.19.2 openai-whisper-20240930 openunmix-1.3.0 optuna-4.0.0 orjson-3.10.9 packaging-24.1 pandas-2.2.3 pillow-10.4.0 platformdirs-4.3.6 pluggy-1.5.0 pooch-1.8.2 primePy-1.3 protobuf-5.28.2 pyaml-24.9.0 pyannote.audio-3.3.1 pyannote.core-5.0.0 pyannote.database-5.1.0 pyannote.metrics-3.2.1 pyannote.pipeline-3.0.1 pycodestyle-2.12.1 pycparser-2.22 pydantic-2.9.2 pydantic-core-2.23.4 pydub-0.25.1 pyflakes-3.2.0 pygments-2.18.0 pyparsing-3.2.0 pyreadline3-3.5.4 pyrubberband-0.3.0 pytest-8.3.3 python-dateutil-2.9.0.post0 python-multipart-0.0.12 pytorch-lightning-2.4.0 pytorch-metric-learning-2.6.0 pytubefix-8.1.1 pytz-2024.2 pyyaml-6.0.2 referencing-0.35.1 regex-2024.9.11 requests-2.32.3 retrying-1.3.4 rich-13.9.2 rpds-py-0.20.0 ruamel.yaml-0.18.6 ruamel.yaml.clib-0.2.12 ruff-0.7.0 safetensors-0.4.5 scikit-learn-1.5.2 scipy-1.13.1 semantic-version-2.10.0 semver-3.0.2 sentencepiece-0.2.0 shellingham-1.5.4 simplejson-3.19.3 six-1.16.0 sniffio-1.3.1 sortedcontainers-2.4.0 soundfile-0.12.1 soxr-0.5.0.post1 speechbrain-1.0.1 sqlalchemy-2.0.36 starlette-0.40.0 stempeg-0.2.3 submitit-1.5.2 sympy-1.13.3 tabulate-0.9.0 tbb-2021.13.1 tensorboardX-2.6.2.2 threadpoolctl-3.5.0 tiktoken-0.8.0 tokenizers-0.20.1 tomli-2.0.2 tomlkit-0.12.0 torch-2.3.1+cu121 torch-audiomentations-0.11.1 torch-pitch-shift-1.2.5 torchaudio-2.3.1+cu121 torchmetrics-1.5.0 torchvision-0.20.0+cu121 tqdm-4.66.5 transformers-4.45.2 treetable-0.2.5 typer-0.12.5 typing-extensions-4.12.2 tzdata-2024.2 urllib3-2.2.3 uvicorn-0.32.0 uvr-0.1 websockets-12.0 zipp-3.20.2
WARNING: You are using pip version 20.2.3; however, version 24.2 is available.
You should consider upgrading via the 'e:\whisper-webui\venv\scripts\python.exe -m pip install --upgrade pip' command.

Requirements installed successfully.
계속하려면 아무 키나 누르십시오 . . .

이렇게 뜨고   start-webui.bat  실행하면

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "E:\Whisper-WebUI\app.py", line 12, in <module>
    from modules.whisper.whisper_factory import WhisperFactory
  File "E:\Whisper-WebUI\modules\whisper\whisper_factory.py", line 6, in <module>
    from modules.whisper.faster_whisper_inference import FasterWhisperInference
  File "E:\Whisper-WebUI\modules\whisper\faster_whisper_inference.py", line 16, in <module>
    from modules.whisper.whisper_base import WhisperBase
  File "E:\Whisper-WebUI\modules\whisper\whisper_base.py", line 6, in <module>
    import torchaudio
  File "E:\Whisper-WebUI\venv\lib\site-packages\torchaudio\__init__.py", line 13, in <module>
    from . import (  # noqa: F401
  File "E:\Whisper-WebUI\venv\lib\site-packages\torchaudio\compliance\__init__.py", line 1, in <module>
    from . import kaldi
  File "E:\Whisper-WebUI\venv\lib\site-packages\torchaudio\compliance\kaldi.py", line 22, in <module>
    EPSILON = torch.tensor(torch.finfo(torch.float).eps)
E:\Whisper-WebUI\venv\lib\site-packages\torchaudio\compliance\kaldi.py:22: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  EPSILON = torch.tensor(torch.finfo(torch.float).eps)
Traceback (most recent call last):
  File "E:\Whisper-WebUI\app.py", line 12, in <module>
    from modules.whisper.whisper_factory import WhisperFactory
  File "E:\Whisper-WebUI\modules\whisper\whisper_factory.py", line 6, in <module>
    from modules.whisper.faster_whisper_inference import FasterWhisperInference
  File "E:\Whisper-WebUI\modules\whisper\faster_whisper_inference.py", line 16, in <module>
    from modules.whisper.whisper_base import WhisperBase
  File "E:\Whisper-WebUI\modules\whisper\whisper_base.py", line 14, in <module>
    from modules.uvr.music_separator import MusicSeparator
  File "E:\Whisper-WebUI\modules\uvr\music_separator.py", line 11, in <module>
    from uvr.models import MDX, Demucs, VrNetwork, MDXC
ModuleNotFoundError: No module named 'uvr'
"launching the app"
계속하려면 아무 키나 누르십시오 . . .  

실행이 안됩니다..

**Comment by jhj0517** [comment]
@gerberanub 님 안녕하세요.

> gradio-4.44.1

pip 가 굳이 구버전의 `gradio` 를 설치하려는 것을 보아 아마도 구버전 pip의 문제인 것 같습니다.
#345 에서 pip 를 업그레이드 하는 스크립트를 추가하였습니다.

이와 별개로 #345 에서 `torch`도 업그레이드 되었습니다.

새로운 버전의 Web UI 로 다시 다운 받으시면 아마 문제 없이 되실 거예요.

 혹시 문제가 생긴다면 알려주시면 감사합니다.

**Comment by gerberanub** [comment]
답변 감사합니다.
지금 venv 삭제하고  whisper-webui 까지 삭제하고
처음부터 다시 실행했는데도



Traceback (most recent call last):
  File "E:\Whisper-WebUI\app.py", line 12, in <module>
    from modules.whisper.whisper_factory import WhisperFactory
  File "E:\Whisper-WebUI\modules\whisper\whisper_factory.py", line 6, in <module>
    from modules.whisper.faster_whisper_inference import FasterWhisperInference
  File "E:\Whisper-WebUI\modules\whisper\faster_whisper_inference.py", line 16, in <module>
    from modules.whisper.whisper_base import WhisperBase
  File "E:\Whisper-WebUI\modules\whisper\whisper_base.py", line 14, in <module>
    from modules.uvr.music_separator import MusicSeparator
  File "E:\Whisper-WebUI\modules\uvr\music_separator.py", line 11, in <module>
    from uvr.models import MDX, Demucs, VrNetwork, MDXC
  File "E:\Whisper-WebUI\venv\lib\site-packages\uvr\models.py", line 4, in <module>
    from .utils.get_models import download_model, model_exists_in_package, get_model_path
  File "E:\Whisper-WebUI\venv\lib\site-packages\uvr\utils\get_models.py", line 89, in <module>
    def get_model_path(model_name: str, model_dir: str) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
"launching the app"
계속하려면 아무 키나 누르십시오 . . .


이렇게 뜹니다..

**Comment by jhj0517** [comment]
@gerberanub 

> unsupported operand type(s) for |: 'type' and 'NoneType'

헉, 파이썬 3.10 이상 에서만 통하는 문법이 있었군요. 
방금 다시 업데이트 했습니다 ㅠㅠ https://github.com/jhj0517/ultimatevocalremover_api/commit/3543be1349ce601568787b69cca0c1f8acba7c2e

번거롭게 해드려서 죄송하지만 가능하다면 파이썬을 3.10 이상 버전으로 다시 재설치 후 WebUI 도 재설치하시길 바랍니다. 

https://www.python.org/downloads/release/python-3111/

아마 64비트 버전이실테니 위 링크에서 스크롤 가장 밑부분의 [Windows installer (64-bit)](https://www.python.org/ftp/python/3.11.1/python-3.11.1-amd64.exe) 로 다운 받으시면 됩니다.

설치하실 때 Add Python to environment variables 체크 되있는 것만 꼭 확인해주시면 됩니다.

**Comment by gerberanub** [comment]
아 이제 잘됩니다.
감사합니다.
