### ISSUE TITLE
google colab not found error after launching

### ISSUE THREAD

**Issue by joonseo0505** [jhj0517/Whisper-WebUI#347]
**Which OS are you using?**
 - OS: Google Colab
![image](https://github.com/user-attachments/assets/3c8d34ef-7579-4e2c-b548-ac3d7264b7e1)

From google colab, I'm getting not found error from making process : gradio_api/queue/join

is there anyway to make it work?

**Comment by jhj0517** [comment]
Hi. This is fixed in https://github.com/jhj0517/Whisper-WebUI/pull/348.

The [new notebook](https://colab.research.google.com/github/jhj0517/Whisper-WebUI/blob/master/notebook/whisper-webui.ipynb) worked fine.

**Comment by jhj0517** [comment]
I'm closing assuming this is resolved, 
Feel free to reopen it!
