### ISSUE TITLE
Python"launching the app"

### ISSUE THREAD

**Issue by beee1342** [jhj0517/Whisper-WebUI#352]
**어떤 OS를 사용하고 계신가요?
윈도우 10 x64 사용중입니다.

지정된 경로를 찾을 수 없습니다.
Python"launching the app"
계속하려면 아무 키나 누르십시오 . . .

start-webui.bat를 실행시 위와 같이 나오는데 해결방법이 있을까요?..

파이썬 설치시 Add Python 3.10 to PATH 도 체크했고
여러번 재설치를 진행해봐도 동일하네요ㅠ

**Comment by jhj0517** [comment]
안녕하세요 @beee1342 님. 
[`Install.bat`](https://github.com/jhj0517/Whisper-WebUI/blob/master/Install.bat) 을 실행하면 venv 폴더를 생성하고 거기에 관련 패키지들을 전부 설치하도록 되어있는데요,

install.bat 을 먼저 실행하신 후 start-webui.bat 을 실행하셨나요?

**Comment by beee1342** [comment]
@jhj0517 답변 감사합니다.

install.bat 을 먼저 실행 후 실행 했는데도 해당 문구가 뜨더라구요
다만 install.bat 을 실행했을때 아래 문구가 먼저 뜬 후 설치가 진행되는데
이것과 관련이 있을까요?

![KakaoTalk_20241025_192050733](https://github.com/user-attachments/assets/b71e23c7-7e7f-418d-b527-46c7906d6960)

Creating venv...
Pythonchecked the venv folder. now installing requirements..
지정된 경로를 찾을 수 없습니다.

**Comment by jhj0517** [comment]
> 지정된 경로를 찾을 수 없습니다.

어째선지 파이썬이 venv 폴더를 제대로 감지 못하고 있네요..
`venv` 폴더를 완전히 삭제 후 다시 `install.bat` 을 실행해서 설치해보시겠어요?

혹시나 다시 설치해도 안된다면 [Pinokio](https://program.pinokio.computer/#/?id=install) 에서 WebUI 를 사용하는 것을 추천드립니다.

(Pinokio 설치 후 Pinokio에서 Whipser-WebUI 검색 후 설치)

+) 그리고 `venv` 가 생성되지 않으면서 그냥 PC에 패키지들이 전부 설치된 것으로 보이는데요, 
cmd 터미널을 여시고
```
cd "C:\AI\Whisper-WebUI" (Whisper-WebUI 경로)
pip uninstall -r requirements.txt -y
```
로 설치된 패키지들을 정리하실 수 있습니다. (약 5GB 좀 넘는 사이즈입니다.)

**Comment by beee1342** [comment]
@jhj0517 Pinokio 설치 후 잘 사용하고 있습니다 답변 감사드립니다:)
