### ISSUE TITLE
VTT file in Error

### ISSUE THREAD

**Issue by borahanarslan** [jhj0517/Whisper-WebUI#359]
When we select the VTT extension, it adds numbers like in the SRT extension. For example:

WebVTT
1
00:00:00.000 --> 00:00:02.700
xxxxxx
2
00:00:02.740 --> 00:00:03.760
yyyyyyy
3
00:00:03.780 --> 00:00:04.000
zzzzzzz

However, VTT files do not include numbers like 1, 2, 3. You can see an example file at the following link:

https://gist.github.com/samdutton/ca37f3adaf4e23679957b8083e061177

**Comment by jhj0517** [comment]
@borahanarslan Ohh Thanks for reporting.
working on fix.

**Comment by jhj0517** [comment]
Fixed in #360, This should not happen anymore!

**Comment by borahanarslan** [comment]
At the beginning of the line there will be WEBVTT, not WebVTT, all letters will be in capital letters, otherwise it will not be detected.

**Comment by jhj0517** [comment]
I thought it didn't matter. Thanks for the clarification & #361!
