### ISSUE TITLE
Load files from local

### ISSUE THREAD

**Issue by moonjy1120** [jhj0517/Whisper-WebUI#38]
Is it possible to load videos in local storage not uploading??
i use colab and it's taking so long time to upload large videos... i want a direct way to use it

**Comment by jhj0517** [comment]
Hi @moonjy1120 , It seems that this feature would only be used in Colab, 
So I should probably add an argument like `--is_colab_user` and use it.

**Comment by Duc2k2** [comment]
is there a way to do this if i install whisper gui on my PC

**Comment by jhj0517** [comment]
"Input Folder Path" component added.
![image](https://github.com/jhj0517/Whisper-WebUI/assets/97279763/1b52c9e0-664d-4027-8506-cbae2c5554dc)
It will read all media files in the folder and transcribe if it's not empty.

Note that this tab only appears if you use `--colab` args when starting the WebUI.
For example, if you are using the Docker, the command would be :
```
docker run --gpus all -d `
-v /path/to/models:/Whisper-WebUI/models `
-v /path/to/outputs:/Whisper-WebUI/outputs `
-p 7860:7860 `
-it `
whisper-webui:latest --server_name 0.0.0.0 --server_port 7860 --colab
 ```
You need to add `--colab` arg. 
 
Plesae feel free to re-open if you face any problem
