### ISSUE TITLE
whisper-webui behind proxy, cannot download output files

### ISSUE THREAD

**Issue by jefke-glider** [jhj0517/Whisper-WebUI#383]
I am using ubuntu 22.04 behind an apache proxy. Everything works fine, i can transcribe files, youtube, etc.., but i cannot download the output files, because the download button seems to reference to http instead of https. 
I started the app with this command : 
python app.py --whisper_type insanely_fast_whisper --server_name 0.0.0.0 --username ***** --password ******
I can download the uploaded audio file via the button on the right, this is referencing https.
I

**Comment by jhj0517** [comment]
Hi, I don't understand the problem, when you are using apache proxy the download link starts from `http` not `https` so you can't download the files?

I have looked into the problem,
Maybe ssl_verify would help: : https://discuss.huggingface.co/t/how-to-run-gradio-with-0-0-0-0-and-https/38003/2

**Comment by jefke-glider** [comment]
yes indeed, the download link starts from http. When I hover the download link (the size of the output file) there isn't even a prefix to the link in the status bar, but the moment I copy or save as the link, it seems to be http

Jef

**Comment by jefke-glider** [comment]
this did not solve the problem, still http to download the output file

**Comment by jhj0517** [comment]
I tried to reproduce with same CLI arguments, but I was able to download the files even though they're http.
I guess this is difficult to reproduce or something else is problematic to download the file.

**Comment by jefke-glider** [comment]
I found the problem, it was in the apache reverse proxy setting :
         ProxyPreserveHost      On
        ProxyRequests               Off
        ProxyPass                       /        http://whisper:7860/
        ProxyPassReverse         /       http://whisper:7860/

        RequestHeader set X-Forwarded-Proto 'https' env=HTTP

-> removed this env=HTTP and it worked!
Thanks for your time and help! 

Jef Peeraer
University of Antwerp
Departement of Arts
