### ISSUE TITLE
FP16

### ISSUE THREAD

**Issue by Tom-Neverwinter** [jhj0517/Whisper-WebUI#40]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.] 
 - Windows 10

running I keep getting fp16 issues. 

tesla m40/ tesla p40/ nvidia 1080ti for testing purposes. might be good to tell the user these cards are not good at fp16

<s> avx2 may also play an important role? amd 5/9 series  </s>

update: 

int8
worked as intended :)

int8_float32
worked as intended :)

**Comment by jhj0517** [comment]
Hi. Is this issue about the compute type fp16 not working in some gpu?
I would add `compute_type` in "Advanced Parameters" tab soon.

**Comment by jhj0517** [comment]
I'm not 100% sure this would works fine, but I tried to display the available `compute_type` by device in #50. 
Please re-open it if it does not work.
