### ISSUE TITLE
Is it possible to add the ability to load self-selected models?

### ISSUE THREAD

**Issue by kosjd** [jhj0517/Whisper-WebUI#406]
First of all, thank you very much for your open-source project. However, I can only use a few models in the list. Could you add an input box, where I can enter the name of a Huggingface model and have it automatically downloaded and loaded?

**Comment by jhj0517** [comment]
Hi, Thanks for suggestion. I think this is a good idea and would require some minor works.
I'll work on it soon!

**Comment by jhj0517** [comment]
With #407, 
You can now enter the repo id from the huggingface in the models dropdown and use it. 
Models will be automatically downloaded to the model directory. 
(Currently it's only enabled for the `faster-whisper` implementation.)

For example, if you want to use [deepdml/faster-whisper-large-v3-turbo-ct2](https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2), you can enter the repo id in the dropdown:

![image](https://github.com/user-attachments/assets/76487a46-b0a5-4154-b735-ded73b2d83d4)

**Comment by kosjd** [comment]
Great, thanks for your open-source project!
