### ISSUE TITLE
Collapsible Advanced Options & Remember Last Settings

### ISSUE THREAD

**Issue by guansk** [jhj0517/Whisper-WebUI#42]
1. Collapsible Advanced Options: Add a foldable section for advanced prompt settings.

Why: The prompt settings can significantly impact the quality of the generated content. A collapsible section would make it easier to fine-tune these settings without cluttering the UI.

2. Remember Last Settings: Save last-used settings (model, language) as defaults for the next time.

Why: When I need to queue multiple tasks, I have to open multiple windows and input the same settings repeatedly. This feature would save time and effort. Alternatively, adding a queue feature or a default settings option could also solve this issue.

**Comment by jhj0517** [comment]
Hi @guansk . Thanks for the suggestion.
> 1. Collapsible Advanced Options: Add a foldable section for advanced prompt settings.

I'm working on this to "Advanced Options" feature, I'd make commit & PR after dealing with some busy stuff.

> 2. Remember Last Settings: Save last-used settings (model, language) as defaults for the next time.

I agree that user should be able to customize the default values, I'm thinking of making some kind of `default_values.yaml` thing and loading it as default values. Users will be able to modify these defaults directly within the `default_values.yaml`.

**Comment by jhj0517** [comment]
Hi, sorry for the late reply.
The feature for load & cache parameters is applied in #255.

You can update defaults in [default_parameters.yaml](https://github.com/jhj0517/Whisper-WebUI/blob/master/configs/default_parameters.yaml).

If you have any problems with it, please let me know and feel free to  reopen the issue!
