### ISSUE TITLE
Error transcribing file on line Requested float16 compute type

### ISSUE THREAD

**Issue by mavicena21** [jhj0517/Whisper-WebUI#44]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]
I use windows 11 and I always get this problem

Error transcribing file on line Requested float16 compute type, but the target device or backend do not support efficient float16 computation.

what should I do??
![image](https://github.com/jhj0517/Whisper-WebUI/assets/77527946/bbf4d4be-81f3-43ed-864d-b8dd35d61356)

**Comment by jhj0517** [comment]
Hi @mavicena21 , This is fixed in #45.
