### ISSUE TITLE
Can we output simple formatted text instead of subtitles ?

### ISSUE THREAD

**Issue by Mozoloa** [jhj0517/Whisper-WebUI#52]
**Describe the feature you'd like**
Can we output simple formatted text instead of subtitles ? I have no use for subtitles, i'd like to have a paragraph of text of the input file with some basic formatting.

**Comment by jhj0517** [comment]
Hi @Mozoloa! Thanks for the sugesstion.
Adding Raw option makes sense to me! working on it.
