### ISSUE TITLE
Doesn't use GPU

### ISSUE THREAD

**Issue by altair823** [jhj0517/Whisper-WebUI#56]
**Which OS are you using?**
 - OS: Windows11
- python: 3.10
- cuda: 12

When I click to generate subtitle, it won't use GPU at all but only CPUs. Is there other prerequisites or settings that I don't know? 

![image](https://github.com/jhj0517/Whisper-WebUI/assets/46125008/f921cc8c-e016-4f62-8cad-e1c5f7a029b5)
![image](https://github.com/jhj0517/Whisper-WebUI/assets/46125008/1f89a30d-0f95-45dd-9d5a-f88dcdbf1274)

**Comment by jhj0517** [comment]
If you use `user-start-webui.bat` to start webui, it will tell you what device you are using. 
For example :

![image](https://github.com/jhj0517/Whisper-WebUI/assets/97279763/9471e7e7-3fa4-4b84-a1b1-336193af4790)

It says <Device "cuda" is detected> when it will use GPU. 
Could you check it?

**Comment by altair823** [comment]
![image](https://github.com/jhj0517/Whisper-WebUI/assets/46125008/d0cc94dc-542c-472f-9993-b6a00974fa68)

It seems not find cuda or gpu device or something. 
For test, I ran [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and it works with GPU...

**Comment by jamironia** [comment]
Same problem for me too.

cpu : 13900k
gpu : 4070ti

@dot-mario I also tried installing a torch, but failed. How do I install the torch?

**Comment by jhj0517** [comment]
@altair823 , @dot-mario , @jamironia 

I updated Pytorch version to 11.8 in #57, can you test with latest version of this webui?
(I recommend to test it after removing the whole project and reinstalling it)

**Comment by altair823** [comment]
It seems working well! 
Thanks for the update👍

![image](https://github.com/jhj0517/Whisper-WebUI/assets/46125008/243cae86-cc06-4881-8373-346f9745f9be)

**Comment by jamironia** [comment]
@jhj0517 

![image](https://github.com/jhj0517/Whisper-WebUI/assets/148315372/9c06ca98-3894-4a73-acb1-e6f9cd6684fa)


It works!
