### ISSUE TITLE
Distill whisper

### ISSUE THREAD

**Issue by Tom-Neverwinter** [jhj0517/Whisper-WebUI#60]
**Describe the feature you'd like**

New month new version

https://github.com/huggingface/distil-whisper

Seems faster than it's predecessors

**Comment by jsboige** [comment]
Apparently work on faster-whisper might [get stalled](https://github.com/SYSTRAN/faster-whisper/issues/533), but there is that [distinct effort](https://github.com/metame-none/faster-distil-whisper/tree/distil-whisper) to combine both.

**Comment by jhj0517** [comment]
I think it faster-whisper resolved this, please feel free to re-open it the issue persist.
