### ISSUE TITLE
Issue with large-v3

### ISSUE THREAD

**Issue by jwvid** [jhj0517/Whisper-WebUI#63]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]
Windows 10 (nvidia gpu)

When I select the 'large-v3' model and press the generate button, the following message is displayed, and the process does not continue.

`Error transcribing file on line Invalid model size 'large-v3', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large
C:\Whisper-WebUI\venv\lib\site-packages\torch\cuda\memory.py:329: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(`

**Comment by jhj0517** [comment]
large-v3 cannot currently be used in faster-whisper.
If you want to use large-v3, set `DISABLE_FASTER_WHISPER` to true in `user-start-webui.bat` file as it uses the OpenAI whisper implementation.

There is an ongoing issue with :
- [faster-whisper #544](https://github.com/guillaumekln/faster-whisper/issues/544)

**Comment by jurandfantom** [comment]
> large-v3 cannot currently be used in faster-whisper. If you want to use large-v3, set `DISABLE_FASTER_WHISPER` to true in `user-start-webui.bat` file as it uses the OpenAI whisper implementation.
> 
> There is an ongoing issue with :
> 
>     * [faster-whisper #544](https://github.com/guillaumekln/faster-whisper/issues/544)

Thanks for explanation. Sadly I get error and not sure exactly why is that. If I can provide any additional informations/errors, please point me out where look for those. 
![23,11,16 - 14,31,13 - 8892 a](https://github.com/jhj0517/Whisper-WebUI/assets/30580568/cd6dfc92-a333-49da-acbc-8df8242ea44c)

CMD log:

To create a public link, set `share=True` in `launch()`.
Error transcribing file: [WinError 2] The system cannot find the file specified
E:\Magazyn\Grafika\AI\Pinokio\api\whisper-webui.pinokio.git\app\venv\lib\site-packages\torch\cuda\memory.py:329: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(

**Comment by inRm3D** [comment]
https://github.com/SYSTRAN/faster-whisper/pull/578

seems now support v3

**Comment by jhj0517** [comment]
That's right! faster-whisper now supports large-v3, so I'm closing this!
