### ISSUE TITLE
error report：reset_max_memory_allocated

### ISSUE THREAD

**Issue by wzgrx** [jhj0517/Whisper-WebUI#64]
**Which OS are you using?**
 - OS: [ Windows]
 - G:\Soft\Whisper-WebUI\venv\lib\site-packages\torch\cuda\memory.py:329: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(

What does this mean? How to solve it? Thank you.

**Comment by jhj0517** [comment]
That is a warning message (not an error) whenever you call `torch.cuda.reset_max_memory_allocated()`. 
The code has been added to mitigate VRAM issues when using models other than Whisper, such as translation models.
