### ISSUE TITLE
need help with install

### ISSUE THREAD

**Issue by canmanita** [jhj0517/Whisper-WebUI#65]
**Which OS are you using?**
 - OS: Ubuntu 20.04.1 64Bit.

Installing on ubuntu i got this error message. I'm non very good with python and i was wondering if someone could lend a hand.

./start-webui.sh 
venv venv/bin/python

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from modules.whisper_Inference import WhisperInference
  File "/home/whisper/Scaricati/Whisper-WebUI-master/modules/whisper_Inference.py", line 17, in <module>
    class WhisperInference(BaseInterface):
  File "/home/whisper/Scaricati/Whisper-WebUI-master/modules/whisper_Inference.py", line 288, in WhisperInference
    ) -> Tuple[list[dict], float]:
TypeError: 'type' object is not subscriptable

thanks for any help

**Comment by hirowa** [comment]
How did you fix it? @canmanita

**Comment by jhj0517** [comment]
Hi @hirowa, This syntax error happens if you are using a Python version older than 3.9, 
I tried to fix this in #132 so that It should work with older verison of python.
If you try the latest version of this web ui, it should work fine. Please let me know if you still encounter an error.
