### ISSUE TITLE
Model v3 selection

### ISSUE THREAD

**Issue by Tom-Neverwinter** [jhj0517/Whisper-WebUI#70]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]
Windows 10

Error: Invalid model size 'large-v3', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large

**Comment by jhj0517** [comment]
Hi. This shouldn't happen after reinstalling the whole project, 
(or you can remove the venv folder and run "install.bat" again).
Have you tried this?
