### ISSUE TITLE
Having problem with installation, venv folder issue?

### ISSUE THREAD

**Issue by neuralnermal** [jhj0517/Whisper-WebUI#72]
Windows 11

After I run the Install.bat it says installation was successful, but I think there's something wrong with it

![image](https://github.com/jhj0517/Whisper-WebUI/assets/132416432/410a471e-f078-4696-bd48-22ecb7eb27c2)
picrel is what I get when I try to run start-webui.bat

notice the "E:\Whisper-WebUI\\venv" part
there are 2 of \ instead of 1
Maybe it's my PC's fault but it seems "%~dp0" is not working as intended?
Which is weird because other batch scripts with %~dp0 works correctly

Also I noticed when I tried to reinstall from scratch and run Install.bat 
It still says the installation was successful, but it also says couldn't locate Venv folder

**Comment by jhj0517** [comment]
Seeing `Whisper-WebUI\\venv\Scripts\Python.exe` (the double `\`) is completely fine and normal behavior.
Does your web ui not work by running `user-start-webui.bat` after installation?

The recommended way to fix this is to remove your venv folder inside the project and re-run the `install.bat` file.  (it will take maybe 20~30 minutes to finish the installation...)

If you get an error message during installation, please let me know.

**Comment by jhj0517** [comment]
I believe this is fixed by using `os` for the path, 
Please feel free to reopen it if the problem persists.
