### ISSUE TITLE
Change localhost to a different adress

### ISSUE THREAD

**Issue by tingtongdpnw** [jhj0517/Whisper-WebUI#79]
On which file i can change the localhost adress to a specific domain, so that for example other people in the company can use the WebUI?

**Comment by jhj0517** [comment]
You can use some command line arguments to get what you want. 

For example, you can run the project with 
`python app.py --share --username MyUserName --password MyPassword`

This will display a shareable URL and other people will need to know the username and password to use the webUI.

There's a `user-start-webui.bat` file to conveniently use these command line arguments. ( Batch file is for Windows only )
If you don't use Windows, you can just manually enter the cmd line arguments as above. 

Here's the [wiki](https://github.com/jhj0517/Whisper-WebUI/wiki/Command-Line-Arguments) on how to use these arguments.

**Comment by tingtongdpnw** [comment]
I run Whisper-WebUI on an Ubuntu Server, now i put an A-Record with a specific URL, to the IP of the Ubuntu Server. My goal is that once i open from outside the specific URL : example.xy.com , the Whisper-WebUI Website pops out. And btw there is just a user-start-webui.bat but shouldnt there also be user-start-webui.sh (for Linux etc).?

**Comment by tingtongdpnw** [comment]
root@ubuntu:/home//TestWhisoper/Whisper-WebUI# python app.py --share
Use Faster Whisper implementation
Device "cpu" is detected
Traceback (most recent call last):
  File "/home//TestWhisoper/Whisper-WebUI/app.py", line 241, in <module>
    app.launch()
  File "/home//TestWhisoper/Whisper-WebUI/app.py", line 48, in launch
    input_file = gr.Files(type="filepath", label="Upload File here")
  File "/usr/local/lib/python3.10/dist-packages/gradio/templates.py", line 420, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/file.py", line 93, in __init__
    raise ValueError(
ValueError: Invalid value for parameter `type`: filepath. Please choose from one of: ['file', 'binary', 'bytes']

I get this error. Doesnt matter if i also configure an username or password (btw can you show me here a screenshot/example, where you exactly change or put the informations, becaues there are parts in user-start-webui.bat and also in the app.py where you can put username and password information...

**Comment by tingtongdpnw** [comment]
is there anybody who can help me here? im trying following the following thing here: https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx

 i just wanna run it on a specific domain, but im stuck in the part 
"gr.Interface(test, "textbox", "textbox").queue().launch(root_path="/gradio-demo")"

can anyone show just one example how he did it.

**Comment by jhj0517** [comment]
Do you want to set a specific port?
Seeing the [launch option](https://www.gradio.app/docs/interface#interface-launch) would be helpful.
For example if you set 
```
self.app.queue(api_open=False).launch(
   server_name="0.0.0.0",
   server_port="7877"
)
```
in the app.py, Then it will be hosted on `http://0.0.0.0:7877`

**Comment by tingtongdpnw** [comment]
No im still confused and dont get it. yes thats exactly what i want what you said, i definitely dont wanna do it with those Parser arguments --share --server_name Test.com etc... Btw if i would do that in the future, is there away that those links are available more then 72 hours? yes im sure there is one, but also for here i need one specific example with the exact command, for some reason i couldnt find anything.
My goal is to set it up in the app.py file right away, like you said. But i still dont no which exact line i have to change that config, can you just show me where or where exactly to i copy the code block which you send above.  Thank you for your help.

**Comment by tingtongdpnw** [comment]
can you show me here another example with a custom name, and where exactly do you put that in? in which file? @jhj0517

**Comment by tingtongdpnw** [comment]
here also another way: https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx but i dont understand how to setup that part: "gr.Interface(test, "textbox", "textbox").queue().launch(root_path="/gradio-demo")" and where to put it. btw is there also a way to do it with caddy? when i try to reach my domain i get the info:
"
Not Found

The requested URL was not found on this server.
Apache/2.4.10 (Debian) Server at www.test.test.com Port 80"

 but what has apache to do with that? caddy runs on port 80 and nginx on port 81. i dont get it.

**Comment by jhj0517** [comment]
Hi @tingtongdpnw, You can edit this part in `app.py`

https://github.com/jhj0517/Whisper-WebUI/blob/e216a046cf760143abf61cfa411409571a81fe34/app.py#L215-L224

Editing this part into

```
self.app.queue(api_open=False).launch(
   server_name="0.0.0.0",
   server_port="7877"
)
```
will host on `http://0.0.0.0:7877`

**Comment by tingtongdpnw** [comment]
ok now it works, btw you put the port in "", its int so for anyone who does the same do the port editing without ""

ERROR:    [Errno 99] error while attempting to bind on address ('XY.XY.XY.XY', 7860): cannot assign requested address

i get that error, but i already put an A-Record to the domain which i want, so why does it give me that error?

**Comment by tingtongdpnw** [comment]
do you have any answer for the error?

**Comment by jhj0517** [comment]
seeing this [solution](https://github.com/gradio-app/gradio/issues/2024) would be helpful if you run on the server on AWS. 
please feel free to re-open it if issue persist.
