### ISSUE TITLE
Host the WebUI on HuggingFace Spaces for a Larger Audience

### ISSUE THREAD

**Issue by yvrjsharma** [jhj0517/Whisper-WebUI#88]
Congratulations on building a cool web UI! It seems like a very handy tool. Well done!

Have you considered showcasing it on HuggingFace Spaces as well? There could be a few benefits for doing so:
- **Expanded Reach**: Introduce your demo to a larger, AI-focused audience.
- **Seamless Integration**: HuggingFace platform offers great compatibility with popular STT/TTS/T-to-T libraries.
- **Engage the Community**: Your project can benefit from a real-time community feedback and interactions via the 'community' section on your Space.

Additionally, our **Community GPU Grants** might be of interest for a resource support.
We have a [step-by-step guide](https://huggingface.co/docs/hub/spaces-sdks-gradio) explaining the process of creating a gradio sdk on Spaces, in case you're interested. 😊 This is our docs on [Community GPU Grants](https://huggingface.co/docs/hub/spaces-gpus#community-gpu-grants).

**Comment by jhj0517** [comment]
Hi @yvrjsharma, thanks for the introduction!
I've just created a new space [here](https://huggingface.co/spaces/jhj0517/Whisper-WebUI). Hope many people can use it as much as possible.

**Comment by jhj0517** [comment]
After upgrading  GPU resources with [Community GPU Grants](https://huggingface.co/docs/hub/spaces-gpus#community-gpu-grants), 
I couldn't use GPU on the space because of the error of
```
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory Please make sure libcudnn_ops_infer.so.8 is in your library path!
```
It seems to be some CUDA dependency PATH error.
Worked fine when using cpu without [Community GPU Grants](https://huggingface.co/docs/hub/spaces-gpus#community-gpu-grants).
