### ISSUE TITLE
Automatically Download the Output

### ISSUE THREAD

**Issue by tingtongdpnw** [jhj0517/Whisper-WebUI#90]
Is there a possibilty to configure the script or change something, so that the Output which comes out down below, to automatically download? I want the Output file automatically got created after generating the subititle file.

Thank you.

**Comment by jhj0517** [comment]
Hi. If you look at the [outputs](https://github.com/jhj0517/Whisper-WebUI/tree/master/outputs) folder, you can see the subtitle files that are generated after transcription.
