### ISSUE TITLE
Deactivate Advanced_Parameters

### ISSUE THREAD

**Issue by tingtongdpnw** [jhj0517/Whisper-WebUI#91]
Is there a possibility to not show the "Advanced_Parameters". My goal is to leave it on the default setting, so that people who use the WebUI dont get confused.

**Comment by jhj0517** [comment]
Hi. As you can see in the [screenshot](https://github.com/jhj0517/Whisper-WebUI/blob/master/screenshot.png), the "Advanced_Parameters" tab is closed by default with `gr.Accordion("Advanced_Parameters", open=False)`. 
So I personally think that this tab can be easily ignored if users don't know about it.

**Comment by tingtongdpnw** [comment]
Totally agree with you, but my supervisor wants too not show it even, because when old people are using this he thinks they get confused.

**Comment by jhj0517** [comment]
In that case you can set `visible=False`, for example you can change the code to
`with gr.Accordion("Advanced_Parameters", visible=False, open=False):` 
in `app.py` to get what you want.
