### ISSUE TITLE
How to change specific "buttons"

### ISSUE THREAD

**Issue by tingtongdpnw** [jhj0517/Whisper-WebUI#93]
I see that stuff like "No microphone found" or the "Record" button you can find here: Whisper-WebUI/venv/lib/python3.10/site-packages/gradio/templates/frontend/assets/Indexyxyxyxyx

But after changing those the change wont apply. Can you help me there, or am i looking maybe in the wrong folder?

**Comment by tingtongdpnw** [comment]
found the solution, for anyone, you have to clear the cache in your browser and reload it, then the changes will apply!

**Comment by tingtongdpnw** [comment]
but what i cant find or change is "- or -", just between the Drop and Click to upload section. Can you tell me where that is, or is there a possibility to change everything to german?

**Comment by jhj0517** [comment]
I'm not sure about your issue, but if you want to do localization, 
You can change any label of the components in the `app.py`. 
For example, In `gr.Button("GENERATE SUBTITLE FILE", variant="primary")`, You can change it to
`"GENERATE SUBTITLE FILE"` to `"UNTERTITELDATEI ERZEUGEN"`

**Comment by tingtongdpnw** [comment]
<img width="276" alt="Bildschirmfoto 2024-02-08 um 19 11 36" src="https://github.com/jhj0517/Whisper-WebUI/assets/156470116/4b71b8ff-60df-423f-b664-d61fa334c312">

**Comment by tingtongdpnw** [comment]
@jhj0517 jhj0517 , 
<img width="416" alt="Download again?" src="https://github.com/jhj0517/Whisper-WebUI/assets/156470116/aecee5c2-d9cc-458d-ba41-063651185373">

another thing would be: You see on the picture 3.1 MB , once you click on it it downloads the file which you upload anyway, is there a way to remove it? because i couldnt find it in the app.py file or the other files, or is there a way to hide it? 

Thank you.

**Comment by tingtongdpnw** [comment]
@jhj0517 especially i also want to change the names of Tiny, Base, Large, where can i change them?

**Comment by jhj0517** [comment]
You can change the label value of the `gradio` component.
If the problem persists, please reopen it.
