### ISSUE TITLE
youtube dont work 

### ISSUE THREAD

**Issue by test01203** [jhj0517/Whisper-WebUI#96]
![image](https://github.com/jhj0517/Whisper-WebUI/assets/104188844/ab599eae-8807-4d13-a412-82b6b7ff45bd)

**Comment by jhj0517** [comment]
Hi, I just tested Youtube transcription and it worked fine. 
`pytube` uses the open API that youtube provides, so sometimes it doesn't work if there is a problem on the server of the Youtube open API server. 
So it might work fine now.

**Comment by jhj0517** [comment]
It's problem of Youtube API server, 
plesae re open it if the issue persist.

**Comment by robman501a** [comment]
Hi, it's not working with me either. :(
![image](https://github.com/user-attachments/assets/80839720-96e7-40e8-85d8-28cb1f2023b8)
![image](https://github.com/user-attachments/assets/5914d90c-2e6c-4320-8a7a-50263fade9ca)

I've uninstalled the app, and I'm using "run as admin" but that didn't help.

I'm on Windows 11. RTX 3060 12GB VRAM, Ryzen 5600x, 32GB RAM
